// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RapidXamlToolkit
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidRapidXamlPackageString = "c735dfc3-c416-4501-bc33-558e2aaad8c5";
        public static Guid guidRapidXamlPackage = new Guid(guidRapidXamlPackageString);

        public const string guidRapidXamlPackageCmdSetString = "8c20aab1-50b0-4523-8d9d-24d512fa8154";
        public static Guid guidRapidXamlPackageCmdSet = new Guid(guidRapidXamlPackageCmdSetString);

        public const string guidImagesString = "092daafa-627f-4f53-a712-4e3e5fa72e0d";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string GuidVisualStudioXAMLWindowContextMenuString = "4c87b692-1202-46aa-b64c-ef01faec53da";
        public static Guid GuidVisualStudioXAMLWindowContextMenu = new Guid(GuidVisualStudioXAMLWindowContextMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeContextGroup = 0x1100;
        public const int CodeContextMenu = 0x1200;
        public const int CodeContextMenuGroup = 0x1300;
        public const int CodeContextMenuSecondaryGroup = 0x1400;
        public const int XamlContextGroup = 0x2100;
        public const int XamlContextMenu = 0x2200;
        public const int XamlContextMenuGroup = 0x2300;
        public const int XamlContextMenuSecondaryGroup = 0x2400;
        public const int MoveAllHardCodedStringsToResourceFileCommandId = 0x1026;
        public const int FeedbackCommandId = 0x1027;
        public const int bmpCopyAsXaml = 0x0001;
        public const int bmpToolbox = 0x0002;
        public const int bmpCreateView = 0x0003;
        public const int bmpOptions = 0x0004;
        public const int bmpSetDc = 0x0005;
        public const int bmpFeedback = 0x0006;
        public const int IDVisualStudioXAMLWindowContextMenu = 0x0103;
    }
}