//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidXamlToolkit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidXamlToolkit.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find project &apos;{0}&apos; in the solution..
        /// </summary>
        public static string Error_UnableToFindProjectInSolution {
            get {
                return ResourceManager.GetString("Error_UnableToFindProjectInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} row definitions..
        /// </summary>
        public static string Info_AddedRowDefsCount {
            get {
                return ResourceManager.GetString("Info_AddedRowDefsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added XAML to toolbox for {0}.
        /// </summary>
        public static string Info_AddedXamlToToolbox {
            get {
                return ResourceManager.GetString("Info_AddedXamlToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding ColumnDefinitions to grid..
        /// </summary>
        public static string Info_AddingColDefsToGrid {
            get {
                return ResourceManager.GetString("Info_AddingColDefsToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Grid to output..
        /// </summary>
        public static string Info_AddingGridToOutput {
            get {
                return ResourceManager.GetString("Info_AddingGridToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding &apos;{0}&apos; to the output..
        /// </summary>
        public static string Info_AddingPropertyToOutput {
            get {
                return ResourceManager.GetString("Info_AddingPropertyToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing C# code. (v{0}).
        /// </summary>
        public static string Info_AnalyzingCSharpCode {
            get {
                return ResourceManager.GetString("Info_AnalyzingCSharpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing VB code.  (v{0}).
        /// </summary>
        public static string Info_AnalyzingVisualBasicCode {
            get {
                return ResourceManager.GetString("Info_AnalyzingVisualBasicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to add XAML to the Toolbox..
        /// </summary>
        public static string Info_AttemptingoAddToToolbox {
            get {
                return ResourceManager.GetString("Info_AttemptingoAddToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to copy XAML to clipboard..
        /// </summary>
        public static string Info_AttemptingToCopy {
            get {
                return ResourceManager.GetString("Info_AttemptingToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to create View..
        /// </summary>
        public static string Info_AttemptingToCreateView {
            get {
                return ResourceManager.GetString("Info_AttemptingToCreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get sub-properties for known type &apos;{0}&apos;..
        /// </summary>
        public static string Info_CannotGetPropertiesForKnownType {
            get {
                return ResourceManager.GetString("Info_CannotGetPropertiesForKnownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class contains no public properties..
        /// </summary>
        public static string Info_ClassNoPublicProperties {
            get {
                return ResourceManager.GetString("Info_ClassNoPublicProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class contains {0} properties..
        /// </summary>
        public static string Info_ClassPropertyCount {
            get {
                return ResourceManager.GetString("Info_ClassPropertyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied XAML for {0}: {1}.
        /// </summary>
        public static string Info_CopiedXaml {
            get {
                return ResourceManager.GetString("Info_CopiedXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find class definition in file &apos;{0}&apos;.
        /// </summary>
        public static string Info_CouldNotFindClassInFile {
            get {
                return ResourceManager.GetString("Info_CouldNotFindClassInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created file {0}.
        /// </summary>
        public static string Info_CreatedView {
            get {
                return ResourceManager.GetString("Info_CreatedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document contains {0} properties..
        /// </summary>
        public static string Info_DocumentPropertyCount {
            get {
                return ResourceManager.GetString("Info_DocumentPropertyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} elements of enum..
        /// </summary>
        public static string Info_EnumElementCount {
            get {
                return ResourceManager.GetString("Info_EnumElementCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get typeSymbol of property &apos;{0}&apos; assumed to have been nullable..
        /// </summary>
        public static string Info_FailedToGetNullableType {
            get {
                return ResourceManager.GetString("Info_FailedToGetNullableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists..
        /// </summary>
        public static string Info_FileExists {
            get {
                return ResourceManager.GetString("Info_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting output for generic type &apos;{0}&apos;..
        /// </summary>
        public static string Info_FormattingOutputForGenericType {
            get {
                return ResourceManager.GetString("Info_FormattingOutputForGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting output for non-generic type &apos;{0}&apos;..
        /// </summary>
        public static string Info_FormattingOutputForNonGenericType {
            get {
                return ResourceManager.GetString("Info_FormattingOutputForNonGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting output for property &apos;{0}&apos;..
        /// </summary>
        public static string Info_FormattingOutputForProperty {
            get {
                return ResourceManager.GetString("Info_FormattingOutputForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting subproperties inside a grid..
        /// </summary>
        public static string Info_FormattingSubpropertiesInsideGrid {
            get {
                return ResourceManager.GetString("Info_FormattingSubpropertiesInsideGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found mapping for &apos;{0}&apos; as an Enum..
        /// </summary>
        public static string Info_FoundEnumMapping {
            get {
                return ResourceManager.GetString("Info_FoundEnumMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} subproperties..
        /// </summary>
        public static string Info_FoundPropertyCount {
            get {
                return ResourceManager.GetString("Info_FoundPropertyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found sub-property &apos;{0}&apos;..
        /// </summary>
        public static string Info_FoundSubProperty {
            get {
                return ResourceManager.GetString("Info_FoundSubProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found sub-property of unknown type: {0}..
        /// </summary>
        public static string Info_FoundSubPropertyOfUnknownType {
            get {
                return ResourceManager.GetString("Info_FoundSubPropertyOfUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting output for the selection..
        /// </summary>
        public static string Info_GetSelectionOutput {
            get {
                return ResourceManager.GetString("Info_GetSelectionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting output for the class..
        /// </summary>
        public static string Info_GetSingleClassOutput {
            get {
                return ResourceManager.GetString("Info_GetSingleClassOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting output for a single item..
        /// </summary>
        public static string Info_GetSingleItemOutput {
            get {
                return ResourceManager.GetString("Info_GetSingleItemOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting output for a single property..
        /// </summary>
        public static string Info_GetSinglePropertyOutput {
            get {
                return ResourceManager.GetString("Info_GetSinglePropertyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting a generic type..
        /// </summary>
        public static string Info_GettingGenericType {
            get {
                return ResourceManager.GetString("Info_GettingGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting sub-property output for &apos;{0}&apos;..
        /// </summary>
        public static string Info_GettingSubPropertyOutput {
            get {
                return ResourceManager.GetString("Info_GettingSubPropertyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified property as Name=&apos;{0}&apos; Type=&apos;{1}&apos; IsReadOnly=&apos;{2}&apos;..
        /// </summary>
        public static string Info_IdentifiedPropertySummary {
            get {
                return ResourceManager.GetString("Info_IdentifiedPropertySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Commands (v{0}).
        /// </summary>
        public static string Info_IntializingCommands {
            get {
                return ResourceManager.GetString("Info_IntializingCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for mappings that are not read-only..
        /// </summary>
        public static string Info_LookingForReadWriteMappings {
            get {
                return ResourceManager.GetString("Info_LookingForReadWriteMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mapping found for &apos;{0}&apos; as an Enum so now checking by type name..
        /// </summary>
        public static string Info_NoEnumMappingFound {
            get {
                return ResourceManager.GetString("Info_NoEnumMappingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mapping found so using fallback output..
        /// </summary>
        public static string Info_NoMappingFoundUsingFallback {
            get {
                return ResourceManager.GetString("Info_NoMappingFoundUsingFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No properties to provide output for..
        /// </summary>
        public static string Info_NoPropertiesToOutput {
            get {
                return ResourceManager.GetString("Info_NoPropertiesToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XAML added to toolbox..
        /// </summary>
        public static string Info_NothingAddedToToolbox {
            get {
                return ResourceManager.GetString("Info_NothingAddedToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to copy to clipboard..
        /// </summary>
        public static string Info_NothingToCopy {
            get {
                return ResourceManager.GetString("Info_NothingToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not including property &apos;{0}&apos; as it&apos;s on the exclusion list..
        /// </summary>
        public static string Info_NotIncludingExcludedProperty {
            get {
                return ResourceManager.GetString("Info_NotIncludingExcludedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not overwriting &apos;{0}&apos;..
        /// </summary>
        public static string Info_NotOverwritingFile {
            get {
                return ResourceManager.GetString("Info_NotOverwritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No view created..
        /// </summary>
        public static string Info_NoViewCreated {
            get {
                return ResourceManager.GetString("Info_NoViewCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XAML copied..
        /// </summary>
        public static string Info_NoXamlCopied {
            get {
                return ResourceManager.GetString("Info_NoXamlCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwriting &apos;{0}&apos;..
        /// </summary>
        public static string Info_OverwritingFile {
            get {
                return ResourceManager.GetString("Info_OverwritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have problems with this extension, or suggestions for improvement, report them at https://github.com/Microsoft/Rapid-XAML-Toolkit/issues/new/choose .
        /// </summary>
        public static string Info_ProblemsInstructionsAndLink {
            get {
                return ResourceManager.GetString("Info_ProblemsInstructionsAndLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} properties within the selection area..
        /// </summary>
        public static string Info_PropertiesInSelectedAreaCount {
            get {
                return ResourceManager.GetString("Info_PropertiesInSelectedAreaCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to analyze property &apos;{0}&apos;..
        /// </summary>
        public static string Info_PropertyCannotBeAnalyzed {
            get {
                return ResourceManager.GetString("Info_PropertyCannotBeAnalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is read-only so looking for read-only mappings first..
        /// </summary>
        public static string Info_PropertyIsReadOnly {
            get {
                return ResourceManager.GetString("Info_PropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is of type &apos;{1}&apos; which has has no sub-properties..
        /// </summary>
        public static string Info_PropertyTypeHasNoSubProperties {
            get {
                return ResourceManager.GetString("Info_PropertyTypeHasNoSubProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not recognized as generic..
        /// </summary>
        public static string Info_PropertyTypeNotRecognizedAsGeneric {
            get {
                return ResourceManager.GetString("Info_PropertyTypeNotRecognizedAsGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is not read-only so filtering out read-only mappings..
        /// </summary>
        public static string Info_ProperyIsNotReadOnly {
            get {
                return ResourceManager.GetString("Info_ProperyIsNotReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing incrementing integer placeholder..
        /// </summary>
        public static string Info_ReplacingIncIntPlaceholder {
            get {
                return ResourceManager.GetString("Info_ReplacingIncIntPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing repeated integer placeholder..
        /// </summary>
        public static string Info_ReplacingRepIntPlaceholder {
            get {
                return ResourceManager.GetString("Info_ReplacingRepIntPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning: {0}.
        /// </summary>
        public static string Info_ReturningOutput {
            get {
                return ResourceManager.GetString("Info_ReturningOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for mapping for generic type treated as &apos;{0}&apos;..
        /// </summary>
        public static string Info_SearchingForMappingWithGenericWildcard {
            get {
                return ResourceManager.GetString("Info_SearchingForMappingWithGenericWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; has {1} sub-properties..
        /// </summary>
        public static string Info_SubpropertyCount {
            get {
                return ResourceManager.GetString("Info_SubpropertyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the assembly &apos;Microsoft.VisualStudio.Telemetry&apos; so telemetry will not be enabled..
        /// </summary>
        public static string Info_UnableToAccessTelemetry {
            get {
                return ResourceManager.GetString("Info_UnableToAccessTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert RowDefinition (Invalid XAML).
        /// </summary>
        public static string Info_UnableToInsertRowDefinitionInvalidXaml {
            get {
                return ResourceManager.GetString("Info_UnableToInsertRowDefinitionInvalidXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ColumnDefinitions.
        /// </summary>
        public static string Info_UndoContextAddColumnDefinitons {
            get {
                return ResourceManager.GetString("Info_UndoContextAddColumnDefinitons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RowDefinitions and ColumnDefinitions.
        /// </summary>
        public static string Info_UndoContextAddRowAndColumnDefinitions {
            get {
                return ResourceManager.GetString("Info_UndoContextAddRowAndColumnDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RowDefinitions.
        /// </summary>
        public static string Info_UndoContextAddRowDefinitions {
            get {
                return ResourceManager.GetString("Info_UndoContextAddRowDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert RowDefinition.
        /// </summary>
        public static string Info_UndoContextIndertRowDef {
            get {
                return ResourceManager.GetString("Info_UndoContextIndertRowDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using class grouping of &apos;{0}&apos;..
        /// </summary>
        public static string Info_UsingClassGrouping {
            get {
                return ResourceManager.GetString("Info_UsingClassGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button contains hardcoded Content value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringButtonContentMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringButtonContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use hard coded values. Use a localized resource instead..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringExtendedMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringExtendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlock contains hardcoded Text value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringTextblockTextMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringTextblockTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard coded string.
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringTooltip {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views &amp; ViewModels are in the same project.
        /// </summary>
        public static string Options_AllInOneProject {
            get {
                return ResourceManager.GetString("Options_AllInOneProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate that the ViewModels and Views (XAML files) are in the same project..
        /// </summary>
        public static string Options_AllInOneProjectDescription {
            get {
                return ResourceManager.GetString("Options_AllInOneProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt automatic document formatting.
        /// </summary>
        public static string Options_AttemptAutomaticDocumentFormatting {
            get {
                return ResourceManager.GetString("Options_AttemptAutomaticDocumentFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Visual Studio&apos;s automatic document formatting after modifying a document.
        /// </summary>
        public static string Options_AttemptAutomaticDocumentFormattingDescription {
            get {
                return ResourceManager.GetString("Options_AttemptAutomaticDocumentFormattingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string Options_ButtonAdd {
            get {
                return ResourceManager.GetString("Options_ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Options_ButtonCopy {
            get {
                return ResourceManager.GetString("Options_ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string Options_ButtonDelete {
            get {
                return ResourceManager.GetString("Options_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Options_ButtonEdit {
            get {
                return ResourceManager.GetString("Options_ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xport.
        /// </summary>
        public static string Options_ButtonExport {
            get {
                return ResourceManager.GetString("Options_ButtonExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string Options_ButtonImport {
            get {
                return ResourceManager.GetString("Options_ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Options_ButtonNew {
            get {
                return ResourceManager.GetString("Options_ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Options_ButtonOk {
            get {
                return ResourceManager.GetString("Options_ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset.
        /// </summary>
        public static string Options_ButtonReset {
            get {
                return ResourceManager.GetString("Options_ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Set as Active.
        /// </summary>
        public static string Options_ButtonSetAsActive {
            get {
                return ResourceManager.GetString("Options_ButtonSetAsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class grouping:.
        /// </summary>
        public static string Options_ClassGrouping {
            get {
                return ResourceManager.GetString("Options_ClassGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element that encapsulates the elements created for each property when creating XAML for a class..
        /// </summary>
        public static string Options_ClassGroupingDescription {
            get {
                return ResourceManager.GetString("Options_ClassGroupingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code-behind constructor content:.
        /// </summary>
        public static string Options_CodeBehindConstructorContent {
            get {
                return ResourceManager.GetString("Options_CodeBehindConstructorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code that should be added to the constructor of the code-behind file when setting the datacontext..
        /// </summary>
        public static string Options_CodeBehindConstructorContentDescription {
            get {
                return ResourceManager.GetString("Options_CodeBehindConstructorContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code-behind page content:.
        /// </summary>
        public static string Options_CodeBehindPageContent {
            get {
                return ResourceManager.GetString("Options_CodeBehindPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code that should be added to the code-behind file, outside of the constructor, when setting the datacontext..
        /// </summary>
        public static string Options_CodeBehindPageContentDescription {
            get {
                return ResourceManager.GetString("Options_CodeBehindPageContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code-behind file default content:.
        /// </summary>
        public static string Options_CodeBehindPlaceholder {
            get {
                return ResourceManager.GetString("Options_CodeBehindPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default file contents when creating a code-behind file..
        /// </summary>
        public static string Options_CodeBehindPlaceholderDescription {
            get {
                return ResourceManager.GetString("Options_CodeBehindPlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataContext.
        /// </summary>
        public static string Options_DataContextHeader {
            get {
                return ResourceManager.GetString("Options_DataContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default code-behind constructor:.
        /// </summary>
        public static string Options_DefaultCodeBehindConstructor {
            get {
                return ResourceManager.GetString("Options_DefaultCodeBehindConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constuctor of the code-behind file that will be added, if needed and one doesn&apos;t already exist..
        /// </summary>
        public static string Options_DefaultCodeBehindConstructorDescription {
            get {
                return ResourceManager.GetString("Options_DefaultCodeBehindConstructorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable extended logging.
        /// </summary>
        public static string Options_EnableExtendedLogging {
            get {
                return ResourceManager.GetString("Options_EnableExtendedLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the amount of information displayed in the output window. Can be helpful in identifying errors or diagnosing why specific output was produced..
        /// </summary>
        public static string Options_EnableExtendedLoggingDescription {
            get {
                return ResourceManager.GetString("Options_EnableExtendedLoggingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum output:.
        /// </summary>
        public static string Options_EnumMappingOutput {
            get {
                return ResourceManager.GetString("Options_EnumMappingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output used for each element of an enumeration..
        /// </summary>
        public static string Options_EnumMappingOutputDescription {
            get {
                return ResourceManager.GetString("Options_EnumMappingOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback output:.
        /// </summary>
        public static string Options_FallbackOutput {
            get {
                return ResourceManager.GetString("Options_FallbackOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output used for a property when no specific mapping can be applied..
        /// </summary>
        public static string Options_FallbackOutputDescription {
            get {
                return ResourceManager.GetString("Options_FallbackOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Options_GeneralHeader {
            get {
                return ResourceManager.GetString("Options_GeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string Options_GeneralSettingsHeader {
            get {
                return ResourceManager.GetString("Options_GeneralSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only if read-only.
        /// </summary>
        public static string Options_MappingIfReadOnly {
            get {
                return ResourceManager.GetString("Options_MappingIfReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapping should only apply if the property has a public setter..
        /// </summary>
        public static string Options_MappingIfReadOnlyDescription {
            get {
                return ResourceManager.GetString("Options_MappingIfReadOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name filter:.
        /// </summary>
        public static string Options_MappingNameFilter {
            get {
                return ResourceManager.GetString("Options_MappingNameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partial name of the property to match with. Multiple values can be specified if separated by a pipe (|) character..
        /// </summary>
        public static string Options_MappingNameFilterDescription {
            get {
                return ResourceManager.GetString("Options_MappingNameFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        public static string Options_MappingOutput {
            get {
                return ResourceManager.GetString("Options_MappingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output that shoudl be generated if this mapping is used..
        /// </summary>
        public static string Options_MappingOutputDescription {
            get {
                return ResourceManager.GetString("Options_MappingOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappings.
        /// </summary>
        public static string Options_MappingsHeader {
            get {
                return ResourceManager.GetString("Options_MappingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Options_MappingType {
            get {
                return ResourceManager.GetString("Options_MappingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the property to match with. Multiple values can be specified if separated by a pipe (|) character..
        /// </summary>
        public static string Options_MappingTypeDescription {
            get {
                return ResourceManager.GetString("Options_MappingTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming.
        /// </summary>
        public static string Options_NamingHeader {
            get {
                return ResourceManager.GetString("Options_NamingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize solution structure.
        /// </summary>
        public static string Options_NamingVisualizer {
            get {
                return ResourceManager.GetString("Options_NamingVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Options_ProfileName {
            get {
                return ResourceManager.GetString("Options_ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Toolkit - Edit Profile.
        /// </summary>
        public static string Options_ProfilePageTitle {
            get {
                return ResourceManager.GetString("Options_ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles:.
        /// </summary>
        public static string Options_ProfilesSectionHeader {
            get {
                return ResourceManager.GetString("Options_ProfilesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure and Naming.
        /// </summary>
        public static string Options_StructureAndNamingHeader {
            get {
                return ResourceManager.GetString("Options_StructureAndNamingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project strucutre.
        /// </summary>
        public static string Options_StrucutreHeader {
            get {
                return ResourceManager.GetString("Options_StrucutreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-property output:.
        /// </summary>
        public static string Options_SubPropertyOutput {
            get {
                return ResourceManager.GetString("Options_SubPropertyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output used for each property of a generic type..
        /// </summary>
        public static string Options_SubPropertyOutputDescription {
            get {
                return ResourceManager.GetString("Options_SubPropertyOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This UI is temporary and will change before release.
        /// </summary>
        public static string Options_TemporaryUiNotice {
            get {
                return ResourceManager.GetString("Options_TemporaryUiNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel directory name:.
        /// </summary>
        public static string Options_ViewModelDirectoryName {
            get {
                return ResourceManager.GetString("Options_ViewModelDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the folder that contains the ViewModels..
        /// </summary>
        public static string Options_ViewModelDirectoryNameDescription {
            get {
                return ResourceManager.GetString("Options_ViewModelDirectoryNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel file suffix:.
        /// </summary>
        public static string Options_ViewModelFileSuffix {
            get {
                return ResourceManager.GetString("Options_ViewModelFileSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text appended to the end of the name of each ViewModel..
        /// </summary>
        public static string Options_ViewModelFileSuffixDescription {
            get {
                return ResourceManager.GetString("Options_ViewModelFileSuffixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel project suffix:.
        /// </summary>
        public static string Options_ViewModelProjectSuffix {
            get {
                return ResourceManager.GetString("Options_ViewModelProjectSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text from the end of the name of the project that contains the ViewModels. .
        /// </summary>
        public static string Options_ViewModelProjectSuffixDescription {
            get {
                return ResourceManager.GetString("Options_ViewModelProjectSuffixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid placeholder detected: {0}.
        /// </summary>
        public static string Options_Warn_InvalidPlaceholders {
            get {
                return ResourceManager.GetString("Options_Warn_InvalidPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown placeholder detected: {0}.
        /// </summary>
        public static string Options_Warn_UnknownPlaceholders {
            get {
                return ResourceManager.GetString("Options_Warn_UnknownPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not leave blank. Use &apos;{0}&apos; if no output is required..
        /// </summary>
        public static string Options_Warn_UseNoOutputNotBlank {
            get {
                return ResourceManager.GetString("Options_Warn_UseNoOutputNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML file directory name:.
        /// </summary>
        public static string Options_XamlFileDirectoryName {
            get {
                return ResourceManager.GetString("Options_XamlFileDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the folder that contains the Views (XAML files.).
        /// </summary>
        public static string Options_XamlFileDirectoryNameDescription {
            get {
                return ResourceManager.GetString("Options_XamlFileDirectoryNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML file suffix:.
        /// </summary>
        public static string Options_XamlFileSuffix {
            get {
                return ResourceManager.GetString("Options_XamlFileSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text appended to the end of the name of each View (XAML file.).
        /// </summary>
        public static string Options_XamlFileSuffixDescription {
            get {
                return ResourceManager.GetString("Options_XamlFileSuffixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML page attribute:.
        /// </summary>
        public static string Options_XamlPageAttribute {
            get {
                return ResourceManager.GetString("Options_XamlPageAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute that should be added ot the top level XAMLelement when setting the datacontext..
        /// </summary>
        public static string Options_XamlPageAttributeDescription {
            get {
                return ResourceManager.GetString("Options_XamlPageAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML file default content:.
        /// </summary>
        public static string Options_XamlPlaceholder {
            get {
                return ResourceManager.GetString("Options_XamlPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default file contents when creating a new XAML file..
        /// </summary>
        public static string Options_XamlPlaceholderDescription {
            get {
                return ResourceManager.GetString("Options_XamlPlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML project suffix:.
        /// </summary>
        public static string Options_XamlProjectSuffix {
            get {
                return ResourceManager.GetString("Options_XamlProjectSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text from the end of the name of the project that contains the Views (XAML files.).
        /// </summary>
        public static string Options_XamlProjectSuffixDescription {
            get {
                return ResourceManager.GetString("Options_XamlProjectSuffixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Toolkit.
        /// </summary>
        public static string Package__106 {
            get {
                return ResourceManager.GetString("Package__106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Package__107 {
            get {
                return ResourceManager.GetString("Package__107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Toolkit.
        /// </summary>
        public static string Package__110 {
            get {
                return ResourceManager.GetString("Package__110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools to accelerate XAML app development.
        /// </summary>
        public static string Package__112 {
            get {
                return ResourceManager.GetString("Package__112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete profile &apos;{0}&apos;?.
        /// </summary>
        public static string Prompt_ConfirmDeleteProfileMessage {
            get {
                return ResourceManager.GetString("Prompt_ConfirmDeleteProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string Prompt_ConfirmDeleteProfileTitle {
            get {
                return ResourceManager.GetString("Prompt_ConfirmDeleteProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting profiles will cause you to lose any changes. Are you sure?.
        /// </summary>
        public static string Prompt_ConfirmResetProfilesMessage {
            get {
                return ResourceManager.GetString("Prompt_ConfirmResetProfilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm reset.
        /// </summary>
        public static string Prompt_ConfirmResetProfilesTitle {
            get {
                return ResourceManager.GetString("Prompt_ConfirmResetProfilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        public static string Prompt_FileExistsTitle {
            get {
                return ResourceManager.GetString("Prompt_FileExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following issues prevented the profile from being imported:
        ///
        ///- {0}.
        /// </summary>
        public static string Prompt_ImportFailedMessage {
            get {
                return ResourceManager.GetString("Prompt_ImportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import profile.
        /// </summary>
        public static string Prompt_ImportFailedTitle {
            get {
                return ResourceManager.GetString("Prompt_ImportFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to override the existing file?.
        /// </summary>
        public static string Propt_FileExistsMessage {
            get {
                return ResourceManager.GetString("Propt_FileExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the Output window pane..
        /// </summary>
        public static string UI_AccessingOutputPaneFailed {
            get {
                return ResourceManager.GetString("UI_AccessingOutputPaneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}    [*ACTIVE*].
        /// </summary>
        public static string UI_ActiveProfileName {
            get {
                return ResourceManager.GetString("UI_ActiveProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (copy).
        /// </summary>
        public static string UI_CopiedProfileName {
            get {
                return ResourceManager.GetString("UI_CopiedProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the Output window pane..
        /// </summary>
        public static string UI_CreatingOutputPaneFailed {
            get {
                return ResourceManager.GetString("UI_CreatingOutputPaneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string UI_NewProfileDefaultName {
            get {
                return ResourceManager.GetString("UI_NewProfileDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- No accessible properties when copying as XAML --&gt;.
        /// </summary>
        public static string UI_NoPropertiesXaml {
            get {
                return ResourceManager.GetString("UI_NoPropertiesXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XAML copied. No profiles configured..
        /// </summary>
        public static string UI_NoXamlCopiedNoProfilesConfigured {
            get {
                return ResourceManager.GetString("UI_NoXamlCopiedNoProfilesConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Profile.
        /// </summary>
        public static string UI_ProfileFilterDescription {
            get {
                return ResourceManager.GetString("UI_ProfileFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Toolkit.
        /// </summary>
        public static string UI_RxtOutputPaneTitle {
            get {
                return ResourceManager.GetString("UI_RxtOutputPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} and {2} other properties.
        /// </summary>
        public static string UI_SelectionMoreThanThreeNames {
            get {
                return ResourceManager.GetString("UI_SelectionMoreThanThreeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} and 1 other property.
        /// </summary>
        public static string UI_SelectionThreeNames {
            get {
                return ResourceManager.GetString("UI_SelectionThreeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1}.
        /// </summary>
        public static string UI_SelectionTwoNames {
            get {
                return ResourceManager.GetString("UI_SelectionTwoNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML.
        /// </summary>
        public static string UI_ToolboxGroupHeader {
            get {
                return ResourceManager.GetString("UI_ToolboxGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML.
        /// </summary>
        public static string VSCT__ContextMenu {
            get {
                return ResourceManager.GetString("VSCT__ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string VSCT__CopyToClipboardCommandId {
            get {
                return ResourceManager.GetString("VSCT__CopyToClipboardCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create View.
        /// </summary>
        public static string VSCT__CreateViewCommandId {
            get {
                return ResourceManager.GetString("VSCT__CreateViewCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First set an active profile.
        /// </summary>
        public static string VSCT__OpenOptionsCommandId {
            get {
                return ResourceManager.GetString("VSCT__OpenOptionsCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Toolbox.
        /// </summary>
        public static string VSCT__SendToToolboxCommandId {
            get {
                return ResourceManager.GetString("VSCT__SendToToolboxCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Datacontext.
        /// </summary>
        public static string VSCT__SetDatacontextCommandId {
            get {
                return ResourceManager.GetString("VSCT__SetDatacontextCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Row Definition.
        /// </summary>
        public static string VSCT_InsertGridRowDefinitionCommandId {
            get {
                return ResourceManager.GetString("VSCT_InsertGridRowDefinitionCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools to accelerate XAML app development.
        /// </summary>
        public static string VSIX__LocalizedDescription {
            get {
                return ResourceManager.GetString("VSIX__LocalizedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Toolkit.
        /// </summary>
        public static string VSIX__LocalizedName {
            get {
                return ResourceManager.GetString("VSIX__LocalizedName", resourceCulture);
            }
        }
    }
}
