folder: docs/ # The folder required to be parsed
httpsOnly: true # enforce only HTTPS links
pullRequestReview: true # If you want a nice review in your pull requests
ignore: 
  files:
    - ./warnings/_template.md # Relative path from the folder shared above
