//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetNoFocusCandidateFound(DependencyObject obj)
        => (ICommand)obj.GetValue(NoFocusCandidateFoundProperty);

    public static void SetNoFocusCandidateFound(DependencyObject obj, ICommand value)
        => obj.SetValue(NoFocusCandidateFoundProperty, value);

    public static readonly DependencyProperty NoFocusCandidateFoundProperty =
        DependencyProperty.RegisterAttached("NoFocusCandidateFound", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnNoFocusCandidateFoundChanged));

    private static void OnNoFocusCandidateFoundChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "NoFocusCandidateFound" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
