//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetDragOver(DependencyObject obj)
        => (ICommand)obj.GetValue(DragOverProperty);

    public static void SetDragOver(DependencyObject obj, ICommand value)
        => obj.SetValue(DragOverProperty, value);

    public static readonly DependencyProperty DragOverProperty =
        DependencyProperty.RegisterAttached("DragOver", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnDragOverChanged));

    private static void OnDragOverChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "DragOver" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
