//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetProcessKeyboardAccelerators(DependencyObject obj)
        => (ICommand)obj.GetValue(ProcessKeyboardAcceleratorsProperty);

    public static void SetProcessKeyboardAccelerators(DependencyObject obj, ICommand value)
        => obj.SetValue(ProcessKeyboardAcceleratorsProperty, value);

    public static readonly DependencyProperty ProcessKeyboardAcceleratorsProperty =
        DependencyProperty.RegisterAttached("ProcessKeyboardAccelerators", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnProcessKeyboardAcceleratorsChanged));

    private static void OnProcessKeyboardAcceleratorsChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "ProcessKeyboardAccelerators" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
