//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetPointerCanceled(DependencyObject obj)
        => (ICommand)obj.GetValue(PointerCanceledProperty);

    public static void SetPointerCanceled(DependencyObject obj, ICommand value)
        => obj.SetValue(PointerCanceledProperty, value);

    public static readonly DependencyProperty PointerCanceledProperty =
        DependencyProperty.RegisterAttached("PointerCanceled", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnPointerCanceledChanged));

    private static void OnPointerCanceledChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "PointerCanceled" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
