//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetPointerMoved(DependencyObject obj)
        => (ICommand)obj.GetValue(PointerMovedProperty);

    public static void SetPointerMoved(DependencyObject obj, ICommand value)
        => obj.SetValue(PointerMovedProperty, value);

    public static readonly DependencyProperty PointerMovedProperty =
        DependencyProperty.RegisterAttached("PointerMoved", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnPointerMovedChanged));

    private static void OnPointerMovedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "PointerMoved" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
