//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetDragLeave(DependencyObject obj)
        => (ICommand)obj.GetValue(DragLeaveProperty);

    public static void SetDragLeave(DependencyObject obj, ICommand value)
        => obj.SetValue(DragLeaveProperty, value);

    public static readonly DependencyProperty DragLeaveProperty =
        DependencyProperty.RegisterAttached("DragLeave", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnDragLeaveChanged));

    private static void OnDragLeaveChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "DragLeave" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
