//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml.WinUI;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetLostFocus(DependencyObject obj)
        => (ICommand)obj.GetValue(LostFocusProperty);

    public static void SetLostFocus(DependencyObject obj, ICommand value)
        => obj.SetValue(LostFocusProperty, value);

    public static readonly DependencyProperty LostFocusProperty =
        DependencyProperty.RegisterAttached("LostFocus", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnLostFocusChanged));

    private static void OnLostFocusChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "LostFocus" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
