//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml.WinUI;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetPointerExited(DependencyObject obj)
        => (ICommand)obj.GetValue(PointerExitedProperty);

    public static void SetPointerExited(DependencyObject obj, ICommand value)
        => obj.SetValue(PointerExitedProperty, value);

    public static readonly DependencyProperty PointerExitedProperty =
        DependencyProperty.RegisterAttached("PointerExited", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnPointerExitedChanged));

    private static void OnPointerExitedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "PointerExited" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
