//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetDragEnter(DependencyObject obj)
        => (ICommand)obj.GetValue(DragEnterProperty);

    public static void SetDragEnter(DependencyObject obj, ICommand value)
        => obj.SetValue(DragEnterProperty, value);

    public static readonly DependencyProperty DragEnterProperty =
        DependencyProperty.RegisterAttached("DragEnter", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnDragEnterChanged));

    private static void OnDragEnterChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "DragEnter" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
