//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml.WinUI;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetManipulationInertiaStarting(DependencyObject obj)
        => (ICommand)obj.GetValue(ManipulationInertiaStartingProperty);

    public static void SetManipulationInertiaStarting(DependencyObject obj, ICommand value)
        => obj.SetValue(ManipulationInertiaStartingProperty, value);

    public static readonly DependencyProperty ManipulationInertiaStartingProperty =
        DependencyProperty.RegisterAttached("ManipulationInertiaStarting", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnManipulationInertiaStartingChanged));

    private static void OnManipulationInertiaStartingChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "ManipulationInertiaStarting" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
