//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml.WinUI;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetPointerReleased(DependencyObject obj)
        => (ICommand)obj.GetValue(PointerReleasedProperty);

    public static void SetPointerReleased(DependencyObject obj, ICommand value)
        => obj.SetValue(PointerReleasedProperty, value);

    public static readonly DependencyProperty PointerReleasedProperty =
        DependencyProperty.RegisterAttached("PointerReleased", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnPointerReleasedChanged));

    private static void OnPointerReleasedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "PointerReleased" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
