//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetAccessKeyDisplayRequested(DependencyObject obj)
        => (ICommand)obj.GetValue(AccessKeyDisplayRequestedProperty);

    public static void SetAccessKeyDisplayRequested(DependencyObject obj, ICommand value)
        => obj.SetValue(AccessKeyDisplayRequestedProperty, value);

    public static readonly DependencyProperty AccessKeyDisplayRequestedProperty =
        DependencyProperty.RegisterAttached("AccessKeyDisplayRequested", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnAccessKeyDisplayRequestedChanged));

    private static void OnAccessKeyDisplayRequestedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "AccessKeyDisplayRequested" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
