//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetBringIntoViewRequested(DependencyObject obj)
        => (ICommand)obj.GetValue(BringIntoViewRequestedProperty);

    public static void SetBringIntoViewRequested(DependencyObject obj, ICommand value)
        => obj.SetValue(BringIntoViewRequestedProperty, value);

    public static readonly DependencyProperty BringIntoViewRequestedProperty =
        DependencyProperty.RegisterAttached("BringIntoViewRequested", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnBringIntoViewRequestedChanged));

    private static void OnBringIntoViewRequestedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "BringIntoViewRequested" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
