//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetManipulationDelta(DependencyObject obj)
        => (ICommand)obj.GetValue(ManipulationDeltaProperty);

    public static void SetManipulationDelta(DependencyObject obj, ICommand value)
        => obj.SetValue(ManipulationDeltaProperty, value);

    public static readonly DependencyProperty ManipulationDeltaProperty =
        DependencyProperty.RegisterAttached("ManipulationDelta", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnManipulationDeltaChanged));

    private static void OnManipulationDeltaChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "ManipulationDelta" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
