//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml.WinUI;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetDragStarting(DependencyObject obj)
        => (ICommand)obj.GetValue(DragStartingProperty);

    public static void SetDragStarting(DependencyObject obj, ICommand value)
        => obj.SetValue(DragStartingProperty, value);

    public static readonly DependencyProperty DragStartingProperty =
        DependencyProperty.RegisterAttached("DragStarting", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnDragStartingChanged));

    private static void OnDragStartingChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "DragStarting" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
