//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml.WinUI;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetPointerEntered(DependencyObject obj)
        => (ICommand)obj.GetValue(PointerEnteredProperty);

    public static void SetPointerEntered(DependencyObject obj, ICommand value)
        => obj.SetValue(PointerEnteredProperty, value);

    public static readonly DependencyProperty PointerEnteredProperty =
        DependencyProperty.RegisterAttached("PointerEntered", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnPointerEnteredChanged));

    private static void OnPointerEnteredChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "PointerEntered" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
