//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetKeyUp(DependencyObject obj)
        => (ICommand)obj.GetValue(KeyUpProperty);

    public static void SetKeyUp(DependencyObject obj, ICommand value)
        => obj.SetValue(KeyUpProperty, value);

    public static readonly DependencyProperty KeyUpProperty =
        DependencyProperty.RegisterAttached("KeyUp", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnKeyUpChanged));

    private static void OnKeyUpChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "KeyUp" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
