//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetDropCompleted(DependencyObject obj)
        => (ICommand)obj.GetValue(DropCompletedProperty);

    public static void SetDropCompleted(DependencyObject obj, ICommand value)
        => obj.SetValue(DropCompletedProperty, value);

    public static readonly DependencyProperty DropCompletedProperty =
        DependencyProperty.RegisterAttached("DropCompleted", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnDropCompletedChanged));

    private static void OnDropCompletedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "DropCompleted" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
