//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetGettingFocus(DependencyObject obj)
        => (ICommand)obj.GetValue(GettingFocusProperty);

    public static void SetGettingFocus(DependencyObject obj, ICommand value)
        => obj.SetValue(GettingFocusProperty, value);

    public static readonly DependencyProperty GettingFocusProperty =
        DependencyProperty.RegisterAttached("GettingFocus", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnGettingFocusChanged));

    private static void OnGettingFocusChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "GettingFocus" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
