//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetManipulationStarting(DependencyObject obj)
        => (ICommand)obj.GetValue(ManipulationStartingProperty);

    public static void SetManipulationStarting(DependencyObject obj, ICommand value)
        => obj.SetValue(ManipulationStartingProperty, value);

    public static readonly DependencyProperty ManipulationStartingProperty =
        DependencyProperty.RegisterAttached("ManipulationStarting", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnManipulationStartingChanged));

    private static void OnManipulationStartingChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "ManipulationStarting" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
