//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetTapped(DependencyObject obj)
        => (ICommand)obj.GetValue(TappedProperty);

    public static void SetTapped(DependencyObject obj, ICommand value)
        => obj.SetValue(TappedProperty, value);

    public static readonly DependencyProperty TappedProperty =
        DependencyProperty.RegisterAttached("Tapped", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnTappedChanged));

    private static void OnTappedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "Tapped" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
