//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetAccessKeyDisplayDismissed(DependencyObject obj)
        => (ICommand)obj.GetValue(AccessKeyDisplayDismissedProperty);

    public static void SetAccessKeyDisplayDismissed(DependencyObject obj, ICommand value)
        => obj.SetValue(AccessKeyDisplayDismissedProperty, value);

    public static readonly DependencyProperty AccessKeyDisplayDismissedProperty =
        DependencyProperty.RegisterAttached("AccessKeyDisplayDismissed", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnAccessKeyDisplayDismissedChanged));

    private static void OnAccessKeyDisplayDismissedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "AccessKeyDisplayDismissed" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
