//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetContextCanceled(DependencyObject obj)
        => (ICommand)obj.GetValue(ContextCanceledProperty);

    public static void SetContextCanceled(DependencyObject obj, ICommand value)
        => obj.SetValue(ContextCanceledProperty, value);

    public static readonly DependencyProperty ContextCanceledProperty =
        DependencyProperty.RegisterAttached("ContextCanceled", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnContextCanceledChanged));

    private static void OnContextCanceledChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "ContextCanceled" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
