//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml.WinUI;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetManipulationCompleted(DependencyObject obj)
        => (ICommand)obj.GetValue(ManipulationCompletedProperty);

    public static void SetManipulationCompleted(DependencyObject obj, ICommand value)
        => obj.SetValue(ManipulationCompletedProperty, value);

    public static readonly DependencyProperty ManipulationCompletedProperty =
        DependencyProperty.RegisterAttached("ManipulationCompleted", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnManipulationCompletedChanged));

    private static void OnManipulationCompletedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "ManipulationCompleted" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
