//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml.WinUI;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetLosingFocus(DependencyObject obj)
        => (ICommand)obj.GetValue(LosingFocusProperty);

    public static void SetLosingFocus(DependencyObject obj, ICommand value)
        => obj.SetValue(LosingFocusProperty, value);

    public static readonly DependencyProperty LosingFocusProperty =
        DependencyProperty.RegisterAttached("LosingFocus", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnLosingFocusChanged));

    private static void OnLosingFocusChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "LosingFocus" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
