//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml.WinUI;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetPointerPressed(DependencyObject obj)
        => (ICommand)obj.GetValue(PointerPressedProperty);

    public static void SetPointerPressed(DependencyObject obj, ICommand value)
        => obj.SetValue(PointerPressedProperty, value);

    public static readonly DependencyProperty PointerPressedProperty =
        DependencyProperty.RegisterAttached("PointerPressed", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnPointerPressedChanged));

    private static void OnPointerPressedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "PointerPressed" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
