//<auto-generated />
using System.Windows.Input;
using Microsoft.UI.Xaml;
using Microsoft.Xaml.Interactivity;
using Microsoft.Xaml.Interactions.Core;

namespace RapidXaml;

public partial class EventToCommand : DependencyObject
{
    public static ICommand GetPreviewKeyUp(DependencyObject obj)
        => (ICommand)obj.GetValue(PreviewKeyUpProperty);

    public static void SetPreviewKeyUp(DependencyObject obj, ICommand value)
        => obj.SetValue(PreviewKeyUpProperty, value);

    public static readonly DependencyProperty PreviewKeyUpProperty =
        DependencyProperty.RegisterAttached("PreviewKeyUp", typeof(ICommand), typeof(EventToCommand), new PropertyMetadata(null, OnPreviewKeyUpChanged));

    private static void OnPreviewKeyUpChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is UIElement uie)
        {
            // Clear any existing behavior(s)
            Interaction.SetBehaviors(uie, null);

            // Add the new one if there is one
            if (e.NewValue is ICommand newCmd)
            {
                var etb = new EventTriggerBehavior { EventName = "PreviewKeyUp" };
                etb.Actions.Add(new InvokeCommandAction { Command = newCmd });

                Interaction.SetBehaviors(uie, new BehaviorCollection { etb });
            }
        }
    }
}
