//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidXamlToolkit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidXamlToolkit.Resources.StringRes", typeof(StringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out-dated configuration detected. See https://github.com/mrlacey/Rapid-XAML-Toolkit/blob/dev/CHANGELOG.md.
        /// </summary>
        public static string Error_OutdatedConfigurationDetected2 {
            get {
                return ResourceManager.GetString("Error_OutdatedConfigurationDetected2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find project &apos;{0}&apos; in the solution..
        /// </summary>
        public static string Error_UnableToFindProjectInSolution {
            get {
                return ResourceManager.GetString("Error_UnableToFindProjectInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred while parsing XAML..
        /// </summary>
        public static string Error_XamlAnalysisDescription {
            get {
                return ResourceManager.GetString("Error_XamlAnalysisDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log an issue to https://github.com/mrlacey/Rapid-XAML-Toolkit/issues Reason: {0}.
        /// </summary>
        public static string Error_XamlAnalysisExtendedMessage {
            get {
                return ResourceManager.GetString("Error_XamlAnalysisExtendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} row definitions..
        /// </summary>
        public static string Info_AddedRowDefsCount {
            get {
                return ResourceManager.GetString("Info_AddedRowDefsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added XAML to toolbox for {0}.
        /// </summary>
        public static string Info_AddedXamlToToolbox {
            get {
                return ResourceManager.GetString("Info_AddedXamlToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding attribute fallback..
        /// </summary>
        public static string Info_AddingAttributeFallback {
            get {
                return ResourceManager.GetString("Info_AddingAttributeFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding ColumnDefinitions to grid..
        /// </summary>
        public static string Info_AddingColDefsToGrid {
            get {
                return ResourceManager.GetString("Info_AddingColDefsToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Grid to output..
        /// </summary>
        public static string Info_AddingGridToOutput {
            get {
                return ResourceManager.GetString("Info_AddingGridToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding &apos;{0}&apos; to the output..
        /// </summary>
        public static string Info_AddingMemberToOutput {
            get {
                return ResourceManager.GetString("Info_AddingMemberToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding &apos;{0}&apos; to the output..
        /// </summary>
        public static string Info_AddingPropertyToOutput {
            get {
                return ResourceManager.GetString("Info_AddingPropertyToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing C# code. (v{0}).
        /// </summary>
        public static string Info_AnalyzingCSharpCode {
            get {
                return ResourceManager.GetString("Info_AnalyzingCSharpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing VB code.  (v{0}).
        /// </summary>
        public static string Info_AnalyzingVisualBasicCode {
            get {
                return ResourceManager.GetString("Info_AnalyzingVisualBasicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to add XAML to the Toolbox..
        /// </summary>
        public static string Info_AttemptingoAddToToolbox {
            get {
                return ResourceManager.GetString("Info_AttemptingoAddToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to copy XAML to clipboard..
        /// </summary>
        public static string Info_AttemptingToCopy {
            get {
                return ResourceManager.GetString("Info_AttemptingToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to create View..
        /// </summary>
        public static string Info_AttemptingToCreateView {
            get {
                return ResourceManager.GetString("Info_AttemptingToCreateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute not found on property..
        /// </summary>
        public static string Info_AttributeNotFoundOnProperty {
            get {
                return ResourceManager.GetString("Info_AttributeNotFoundOnProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute parameter with index &apos;{0}&apos; not found..
        /// </summary>
        public static string Info_AttributeParameterWIthoutIndex {
            get {
                return ResourceManager.GetString("Info_AttributeParameterWIthoutIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get sub-members for known type &apos;{0}&apos;.
        /// </summary>
        public static string Info_CannotGetMethodsForKnownType {
            get {
                return ResourceManager.GetString("Info_CannotGetMethodsForKnownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get sub-properties for known type &apos;{0}&apos;..
        /// </summary>
        public static string Info_CannotGetPropertiesForKnownType {
            get {
                return ResourceManager.GetString("Info_CannotGetPropertiesForKnownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class contains no public properties..
        /// </summary>
        public static string Info_ClassNoPublicProperties {
            get {
                return ResourceManager.GetString("Info_ClassNoPublicProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class contains {0} properties..
        /// </summary>
        public static string Info_ClassPropertyCount {
            get {
                return ResourceManager.GetString("Info_ClassPropertyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied XAML for {0}: {1}.
        /// </summary>
        public static string Info_CopiedXaml {
            get {
                return ResourceManager.GetString("Info_CopiedXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find class definition in file &apos;{0}&apos;.
        /// </summary>
        public static string Info_CouldNotFindClassInFile {
            get {
                return ResourceManager.GetString("Info_CouldNotFindClassInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created file {0}.
        /// </summary>
        public static string Info_CreatedView {
            get {
                return ResourceManager.GetString("Info_CreatedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected project type as &apos;{0}&apos;..
        /// </summary>
        public static string Info_DetectedProjectType {
            get {
                return ResourceManager.GetString("Info_DetectedProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document contains {0} methods..
        /// </summary>
        public static string Info_DocumentMethodCount {
            get {
                return ResourceManager.GetString("Info_DocumentMethodCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document contains {0} properties..
        /// </summary>
        public static string Info_DocumentPropertyCount {
            get {
                return ResourceManager.GetString("Info_DocumentPropertyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} elements of enum..
        /// </summary>
        public static string Info_EnumElementCount {
            get {
                return ResourceManager.GetString("Info_EnumElementCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand property &apos;{0}&apos;.
        /// </summary>
        public static string Info_ExpandAutoPropertyAnalyzerMessage {
            get {
                return ResourceManager.GetString("Info_ExpandAutoPropertyAnalyzerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property can be expanded.
        /// </summary>
        public static string Info_ExpandAutoPropertyAnalyzerTitle {
            get {
                return ResourceManager.GetString("Info_ExpandAutoPropertyAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get typeSymbol of property &apos;{0}&apos; assumed to have been nullable..
        /// </summary>
        public static string Info_FailedToGetNullableType {
            get {
                return ResourceManager.GetString("Info_FailedToGetNullableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature used: {0}.
        /// </summary>
        public static string Info_FeatureUsage {
            get {
                return ResourceManager.GetString("Info_FeatureUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping &apos;{0}&apos; onto view..
        /// </summary>
        public static string Info_FileDropped {
            get {
                return ResourceManager.GetString("Info_FileDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists..
        /// </summary>
        public static string Info_FileExists {
            get {
                return ResourceManager.GetString("Info_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting output for generic type &apos;{0}&apos;..
        /// </summary>
        public static string Info_FormattingOutputForGenericType {
            get {
                return ResourceManager.GetString("Info_FormattingOutputForGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting output for method &apos;{0}&apos;.
        /// </summary>
        public static string Info_FormattingOutputForMethod {
            get {
                return ResourceManager.GetString("Info_FormattingOutputForMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting output for non-generic type &apos;{0}&apos;..
        /// </summary>
        public static string Info_FormattingOutputForNonGenericType {
            get {
                return ResourceManager.GetString("Info_FormattingOutputForNonGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting output for property &apos;{0}&apos;..
        /// </summary>
        public static string Info_FormattingOutputForProperty {
            get {
                return ResourceManager.GetString("Info_FormattingOutputForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output template: &apos;{0}&apos;.
        /// </summary>
        public static string Info_FormattingRawOutput {
            get {
                return ResourceManager.GetString("Info_FormattingRawOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting subproperties inside a grid..
        /// </summary>
        public static string Info_FormattingSubpropertiesInsideGrid {
            get {
                return ResourceManager.GetString("Info_FormattingSubpropertiesInsideGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found attribute argument: &apos;{0}&apos;=&apos;{1}&apos;.
        /// </summary>
        public static string Info_FoundAttributeArgument {
            get {
                return ResourceManager.GetString("Info_FoundAttributeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found mapping for &apos;{0}&apos; as an Enum..
        /// </summary>
        public static string Info_FoundEnumMapping {
            get {
                return ResourceManager.GetString("Info_FoundEnumMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} subproperties..
        /// </summary>
        public static string Info_FoundPropertyCount {
            get {
                return ResourceManager.GetString("Info_FoundPropertyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found sub-method of unknown type: {0}.
        /// </summary>
        public static string Info_FoundSubMethodOfUnknownType {
            get {
                return ResourceManager.GetString("Info_FoundSubMethodOfUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found sub-property &apos;{0}&apos;..
        /// </summary>
        public static string Info_FoundSubProperty {
            get {
                return ResourceManager.GetString("Info_FoundSubProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found sub-property of unknown type: {0}..
        /// </summary>
        public static string Info_FoundSubPropertyOfUnknownType {
            get {
                return ResourceManager.GetString("Info_FoundSubPropertyOfUnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting output for the selection..
        /// </summary>
        public static string Info_GetSelectionOutput {
            get {
                return ResourceManager.GetString("Info_GetSelectionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting output for the class..
        /// </summary>
        public static string Info_GetSingleClassOutput {
            get {
                return ResourceManager.GetString("Info_GetSingleClassOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting output for a single item..
        /// </summary>
        public static string Info_GetSingleItemOutput {
            get {
                return ResourceManager.GetString("Info_GetSingleItemOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting output for a single method..
        /// </summary>
        public static string Info_GetSingleMethodOutput {
            get {
                return ResourceManager.GetString("Info_GetSingleMethodOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting output for a single property..
        /// </summary>
        public static string Info_GetSinglePropertyOutput {
            get {
                return ResourceManager.GetString("Info_GetSinglePropertyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting a generic type..
        /// </summary>
        public static string Info_GettingGenericType {
            get {
                return ResourceManager.GetString("Info_GettingGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting sub-property output for &apos;{0}&apos;..
        /// </summary>
        public static string Info_GettingSubPropertyOutput {
            get {
                return ResourceManager.GetString("Info_GettingSubPropertyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified property as Name=&apos;{0}&apos; Type=&apos;{1}&apos; IsReadOnly=&apos;{2}&apos;..
        /// </summary>
        public static string Info_IdentifiedPropertySummary {
            get {
                return ResourceManager.GetString("Info_IdentifiedPropertySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Commands (v{0}).
        /// </summary>
        public static string Info_IntializingCommands {
            get {
                return ResourceManager.GetString("Info_IntializingCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known attributes: {0}.
        /// </summary>
        public static string Info_KnownAttributes {
            get {
                return ResourceManager.GetString("Info_KnownAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for mappings that are not read-only..
        /// </summary>
        public static string Info_LookingForReadWriteMappings {
            get {
                return ResourceManager.GetString("Info_LookingForReadWriteMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} methods within the selection area..
        /// </summary>
        public static string Info_MethodsInSelectedAreaCount {
            get {
                return ResourceManager.GetString("Info_MethodsInSelectedAreaCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute parameter named &apos;{0}&apos; not found..
        /// </summary>
        public static string Info_NamedAttributeParameterNotFound {
            get {
                return ResourceManager.GetString("Info_NamedAttributeParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arguments for attribute..
        /// </summary>
        public static string Info_NoArgumentsForAttribute {
            get {
                return ResourceManager.GetString("Info_NoArgumentsForAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mapping found for &apos;{0}&apos; as an Enum so now checking by type name..
        /// </summary>
        public static string Info_NoEnumMappingFound {
            get {
                return ResourceManager.GetString("Info_NoEnumMappingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mapping found for {0} so no output being generated..
        /// </summary>
        public static string Info_NoMappingFoundForMethod {
            get {
                return ResourceManager.GetString("Info_NoMappingFoundForMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mapping found so using fallback output..
        /// </summary>
        public static string Info_NoMappingFoundUsingFallback {
            get {
                return ResourceManager.GetString("Info_NoMappingFoundUsingFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No properties or methods to provide output for..
        /// </summary>
        public static string Info_NoMembersToOutput {
            get {
                return ResourceManager.GetString("Info_NoMembersToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No properties to provide output for..
        /// </summary>
        public static string Info_NoPropertiesToOutput {
            get {
                return ResourceManager.GetString("Info_NoPropertiesToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource file was found in the project. Add one and then try again..
        /// </summary>
        public static string Info_NoResourceFileFound {
            get {
                return ResourceManager.GetString("Info_NoResourceFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XAML added to toolbox..
        /// </summary>
        public static string Info_NothingAddedToToolbox {
            get {
                return ResourceManager.GetString("Info_NothingAddedToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to copy to clipboard..
        /// </summary>
        public static string Info_NothingToCopy {
            get {
                return ResourceManager.GetString("Info_NothingToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not including property &apos;{0}&apos; as it&apos;s on the exclusion list..
        /// </summary>
        public static string Info_NotIncludingExcludedProperty {
            get {
                return ResourceManager.GetString("Info_NotIncludingExcludedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not overwriting &apos;{0}&apos;..
        /// </summary>
        public static string Info_NotOverwritingFile {
            get {
                return ResourceManager.GetString("Info_NotOverwritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No view created..
        /// </summary>
        public static string Info_NoViewCreated {
            get {
                return ResourceManager.GetString("Info_NoViewCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XAML copied..
        /// </summary>
        public static string Info_NoXamlCopied {
            get {
                return ResourceManager.GetString("Info_NoXamlCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output contains placeholder for attribute &apos;{0}&apos;.
        /// </summary>
        public static string Info_OutputContainsAttributePlaceholder {
            get {
                return ResourceManager.GetString("Info_OutputContainsAttributePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwriting &apos;{0}&apos;..
        /// </summary>
        public static string Info_OverwritingFile {
            get {
                return ResourceManager.GetString("Info_OverwritingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have problems with this extension, or suggestions for improvement, report them at https://github.com/mrlacey/Rapid-XAML-Toolkit/issues/new/choose .
        /// </summary>
        public static string Info_ProblemsInstructionsAndLink {
            get {
                return ResourceManager.GetString("Info_ProblemsInstructionsAndLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} properties within the selection area..
        /// </summary>
        public static string Info_PropertiesInSelectedAreaCount {
            get {
                return ResourceManager.GetString("Info_PropertiesInSelectedAreaCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to analyze property &apos;{0}&apos;..
        /// </summary>
        public static string Info_PropertyCannotBeAnalyzed {
            get {
                return ResourceManager.GetString("Info_PropertyCannotBeAnalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is read-only so looking for read-only mappings first..
        /// </summary>
        public static string Info_PropertyIsReadOnly {
            get {
                return ResourceManager.GetString("Info_PropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is of type &apos;{1}&apos; which has has no sub-properties..
        /// </summary>
        public static string Info_PropertyTypeHasNoSubProperties {
            get {
                return ResourceManager.GetString("Info_PropertyTypeHasNoSubProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; not recognized as generic..
        /// </summary>
        public static string Info_PropertyTypeNotRecognizedAsGeneric {
            get {
                return ResourceManager.GetString("Info_PropertyTypeNotRecognizedAsGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is not read-only so filtering out read-only mappings..
        /// </summary>
        public static string Info_ProperyIsNotReadOnly {
            get {
                return ResourceManager.GetString("Info_ProperyIsNotReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing incrementing integer placeholder..
        /// </summary>
        public static string Info_ReplacingIncIntPlaceholder {
            get {
                return ResourceManager.GetString("Info_ReplacingIncIntPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing repeated integer placeholder..
        /// </summary>
        public static string Info_ReplacingRepIntPlaceholder {
            get {
                return ResourceManager.GetString("Info_ReplacingRepIntPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning: {0}.
        /// </summary>
        public static string Info_ReturningOutput {
            get {
                return ResourceManager.GetString("Info_ReturningOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for mapping for generic type treated as &apos;{0}&apos;..
        /// </summary>
        public static string Info_SearchingForMappingWithGenericWildcard {
            get {
                return ResourceManager.GetString("Info_SearchingForMappingWithGenericWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; has {1} sub-properties..
        /// </summary>
        public static string Info_SubpropertyCount {
            get {
                return ResourceManager.GetString("Info_SubpropertyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the assembly &apos;Microsoft.VisualStudio.Telemetry&apos; so telemetry will not be enabled..
        /// </summary>
        public static string Info_UnableToAccessTelemetry {
            get {
                return ResourceManager.GetString("Info_UnableToAccessTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine if extended output is enabled so assuming it is..
        /// </summary>
        public static string Info_UnableToDetermineIfExtendedOutputEnabled {
            get {
                return ResourceManager.GetString("Info_UnableToDetermineIfExtendedOutputEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Drop Handler as extension not yet loaded..
        /// </summary>
        public static string Info_UnableToGetDropHandler {
            get {
                return ResourceManager.GetString("Info_UnableToGetDropHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert RowDefinition (Invalid XAML).
        /// </summary>
        public static string Info_UnableToInsertRowDefinitionInvalidXaml {
            get {
                return ResourceManager.GetString("Info_UnableToInsertRowDefinitionInvalidXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ColumnDefinitions.
        /// </summary>
        public static string Info_UndoContextAddColumnDefinitions {
            get {
                return ResourceManager.GetString("Info_UndoContextAddColumnDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Keyboard property..
        /// </summary>
        public static string Info_UndoContextAddEntryKeyboard {
            get {
                return ResourceManager.GetString("Info_UndoContextAddEntryKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing column definitions.
        /// </summary>
        public static string Info_UndoContextAddMissingColumnDefinitions {
            get {
                return ResourceManager.GetString("Info_UndoContextAddMissingColumnDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing row definitions.
        /// </summary>
        public static string Info_UndoContextAddMissingRowDefinitions {
            get {
                return ResourceManager.GetString("Info_UndoContextAddMissingRowDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RowDefinitions and ColumnDefinitions.
        /// </summary>
        public static string Info_UndoContextAddRowAndColumnDefinitions {
            get {
                return ResourceManager.GetString("Info_UndoContextAddRowAndColumnDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RowDefinitions.
        /// </summary>
        public static string Info_UndoContextAddRowDefinitions {
            get {
                return ResourceManager.GetString("Info_UndoContextAddRowDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add InputScope property..
        /// </summary>
        public static string Info_UndoContextAddTextBoxInputScope {
            get {
                return ResourceManager.GetString("Info_UndoContextAddTextBoxInputScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert RowDefinition.
        /// </summary>
        public static string Info_UndoContextInsertRowDef {
            get {
                return ResourceManager.GetString("Info_UndoContextInsertRowDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move all strings to resource file.
        /// </summary>
        public static string Info_UndoContextMoveStringsToResourceFile {
            get {
                return ResourceManager.GetString("Info_UndoContextMoveStringsToResourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move string to resource file.
        /// </summary>
        public static string Info_UndoContextMoveStringToResourceFile {
            get {
                return ResourceManager.GetString("Info_UndoContextMoveStringToResourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected method type &apos;{0}&apos; cannot be converted to XAML..
        /// </summary>
        public static string Info_UnexpectedMethodType {
            get {
                return ResourceManager.GetString("Info_UnexpectedMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected property type &apos;{0}&apos; cannot be converted to XAML..
        /// </summary>
        public static string Info_UnexpectedPropertyType {
            get {
                return ResourceManager.GetString("Info_UnexpectedPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using class grouping of &apos;{0}&apos;..
        /// </summary>
        public static string Info_UsingClassGrouping {
            get {
                return ResourceManager.GetString("Info_UsingClassGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using profile &apos;{0}&apos;..
        /// </summary>
        public static string Info_UsingProfile {
            get {
                return ResourceManager.GetString("Info_UsingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle both `Checked` and `Unchecked` events if handle one..
        /// </summary>
        public static string Info_XamlAnalysisCheckBoxCheckedAndUncheckedEventsDescription {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisCheckBoxCheckedAndUncheckedEventsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Checked and Unchecked events occur independently. If you handle these events, you should handle both of them to respond to state changes in the check box..
        /// </summary>
        public static string Info_XamlAnalysisCheckBoxCheckedAndUncheckedEventsExtendedMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisCheckBoxCheckedAndUncheckedEventsExtendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle both `Checked` and `Unchecked` events..
        /// </summary>
        public static string Info_XamlAnalysisCheckBoxCheckedAndUncheckedEventsToolTip {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisCheckBoxCheckedAndUncheckedEventsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to use more than the defined number of columns..
        /// </summary>
        public static string Info_XamlAnalysisColumnSpanOverflowDescription {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisColumnSpanOverflowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to span more columns than are defined..
        /// </summary>
        public static string Info_XamlAnalysisColumnSpanOverflowTooltip {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisColumnSpanOverflowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard is not specified for the Entry..
        /// </summary>
        public static string Info_XamlAnalysisEntryWithoutKeyboardDescription {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisEntryWithoutKeyboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifying the keyboard can make it easier for the user to enter the correct value. .
        /// </summary>
        public static string Info_XamlAnalysisEntryWithoutKeyboardExtendedMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisEntryWithoutKeyboardExtendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBarButton contains hard-coded Label value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringAppBarButtonLabelMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringAppBarButtonLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppBarToggleButton contains hard-coded Label value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringAppBarToggleButtonLabelMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringAppBarToggleButtonLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSuggestBox contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringAutoSuggestBoxHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringAutoSuggestBoxHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSuggestBox contains hard-coded Placeholder value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringAutoSuggestBoxPlaceHolderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringAutoSuggestBoxPlaceHolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button contains hard-coded Content value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringButtonContentMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringButtonContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalendarDatePicker contains hard-coded Description value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringCalendarDatePickerDescriptionMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringCalendarDatePickerDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalendarDatePicker contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringCalendarDatePickerHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringCalendarDatePickerHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox contains hard-coded Content value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringCheckboxContentMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringCheckboxContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBox contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringComboboxHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringComboboxHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatePicker contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringDatePickerHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringDatePickerHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use hard-coded values. Use a localized resource instead..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringExtendedMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringExtendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringHubHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringHubHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HubSection contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringHubSectionHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringHubSectionHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperlinkButton contains hard-coded Content value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringHyperlinkButtonContentMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringHyperlinkButtonContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label contains hard-coded Text value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringLabelTextMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringLabelTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuFlyoutItem contains hard-coded Text value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringMenuFlyoutItemTextMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringMenuFlyoutItemTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuFlyoutSubItem contains hard-coded Text value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringMenuFlyoutSubItemTextMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringMenuFlyoutSubItemTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBox contains hard-coded Description value &apos;{0};.
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringPasswordboxDescriptionMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringPasswordboxDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBox contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringPasswordboxHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringPasswordboxHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PivotItem contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringPivotItemHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringPivotItemHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot contains hard-coded Title value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringPivotTitleMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringPivotTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepeatButton contains hard-coded Content value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringRepeatButtonContentMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringRepeatButtonContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RichEditBox contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringRichEditBoxHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringRichEditBoxHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringSliderHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringSliderHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlock contains hard-coded Text value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringTextblockTextMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringTextblockTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringTextboxHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringTextboxHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox contains hard-coded PlaceholderText value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringTextboxPlaceholderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringTextboxPlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimePicker contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringTimePickerHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringTimePickerHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToggleMenuFlyoutItem contains hard-coded Text value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringToggleMenuFlyoutItemTextMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringToggleMenuFlyoutItemTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToggleSwitch contains hard-coded Header value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringToggleSwitchHeaderMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringToggleSwitchHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToggleSwitch contains hard-coded OffContent value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringToggleSwitchOffContentMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringToggleSwitchOffContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToggleSwitch contains hard-coded OnContent value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringToggleSwitchOnContentMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringToggleSwitchOnContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard-coded string.
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringTooltip {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TooltipService contains hard-coded ToolTip value &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisHardcodedStringTooltipServiceToolTipMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisHardcodedStringTooltipServiceToolTipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of undefined Column &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisMissingColumnDefinitionDescription {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisMissingColumnDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The use of undefined columns can lead to unexpected layout behavior. It can also be confusing for other people looking at the code..
        /// </summary>
        public static string Info_XamlAnalysisMissingColumnDefinitionExtendedMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisMissingColumnDefinitionExtendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No corresponding column definition.
        /// </summary>
        public static string Info_XamlAnalysisMissingColumnDefinitionTooltip {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisMissingColumnDefinitionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of undefined Row &apos;{0}&apos;..
        /// </summary>
        public static string Info_XamlAnalysisMissingRowDefinitionDescription {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisMissingRowDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The use of undefined rows can lead to unexpected layout behavior. It can also be confusing for other people looking at the code..
        /// </summary>
        public static string Info_XamlAnalysisMissingRowDefinitionExtendedMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisMissingRowDefinitionExtendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No corresponding row definition.
        /// </summary>
        public static string Info_XamlAnalysisMissingRowDefinitionTooltip {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisMissingRowDefinitionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should begin with an upper case character: {0}.
        /// </summary>
        public static string Info_XamlAnalysisNameTitleCaseDescription {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisNameTitleCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name value should begin with an upper case character..
        /// </summary>
        public static string Info_XamlAnalysisNameTitleCaseToolTip {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisNameTitleCaseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to use more than the defined number of rows..
        /// </summary>
        public static string Info_XamlAnalysisRowSpanOverflowDescription {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisRowSpanOverflowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to span more rows than are defined..
        /// </summary>
        public static string Info_XamlAnalysisRowSpanOverflowTooltip {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisRowSpanOverflowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To receive notification of selection changes, set BindingMode to TwoWay..
        /// </summary>
        public static string Info_XamlAnalysisSetBindingModeToTwoWayDescription {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisSetBindingModeToTwoWayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set BindingMode to TwoWay to be notified of changes..
        /// </summary>
        public static string Info_XamlAnalysisSetBindingModeToTwoWayToolTip {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisSetBindingModeToTwoWayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputScope is not specified for the TextBox..
        /// </summary>
        public static string Info_XamlAnalysisTextBoxWithoutInputScopeDescription {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisTextBoxWithoutInputScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifying the InputScope can make it easier for the user to enter the correct value. .
        /// </summary>
        public static string Info_XamlAnalysisTextBoxWithoutInputScopeExtendedMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisTextBoxWithoutInputScopeExtendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uid should begin with an upper case character: {0}.
        /// </summary>
        public static string Info_XamlAnalysisUidTitleCaseDescription {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisUidTitleCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uid value should begin with an upper case character..
        /// </summary>
        public static string Info_XamlAnalysisUidTitleCaseToolTip {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisUidTitleCaseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use MediaPlayerElement in place of MediaElement..
        /// </summary>
        public static string Info_XamlAnalysisUseMediaPlayerElementDescription {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisUseMediaPlayerElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommend that you use MediaPlayerElement in place of MediaElement. MediaPlayerElement has the same functionality as MediaElement, while also enabling more advanced media playback scenarios. Additionally, all future improvements in media playback will happen in MediaPlayerElement..
        /// </summary>
        public static string Info_XamlAnalysisUseMediaPlayerElementExtendedMessage {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisUseMediaPlayerElementExtendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use MediaPlayerElement in place of MediaElement..
        /// </summary>
        public static string Info_XamlAnalysisUseMediaPlayerElementToolTip {
            get {
                return ResourceManager.GetString("Info_XamlAnalysisUseMediaPlayerElementToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Toolkit.
        /// </summary>
        public static string Package__106 {
            get {
                return ResourceManager.GetString("Package__106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Package__107 {
            get {
                return ResourceManager.GetString("Package__107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Toolkit.
        /// </summary>
        public static string Package__110 {
            get {
                return ResourceManager.GetString("Package__110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools to accelerate XAML app development.
        /// </summary>
        public static string Package__112 {
            get {
                return ResourceManager.GetString("Package__112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete profile &apos;{0}&apos;?.
        /// </summary>
        public static string Prompt_ConfirmDeleteProfileMessage {
            get {
                return ResourceManager.GetString("Prompt_ConfirmDeleteProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string Prompt_ConfirmDeleteProfileTitle {
            get {
                return ResourceManager.GetString("Prompt_ConfirmDeleteProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting profiles will cause you to lose any changes. Are you sure?.
        /// </summary>
        public static string Prompt_ConfirmResetProfilesMessage {
            get {
                return ResourceManager.GetString("Prompt_ConfirmResetProfilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm reset.
        /// </summary>
        public static string Prompt_ConfirmResetProfilesTitle {
            get {
                return ResourceManager.GetString("Prompt_ConfirmResetProfilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        public static string Prompt_FileExistsTitle {
            get {
                return ResourceManager.GetString("Prompt_FileExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following issues prevented the profile from being imported:
        ///
        ///- {0}.
        /// </summary>
        public static string Prompt_ImportFailedMessage {
            get {
                return ResourceManager.GetString("Prompt_ImportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import profile.
        /// </summary>
        public static string Prompt_ImportFailedTitle {
            get {
                return ResourceManager.GetString("Prompt_ImportFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to override the existing file?.
        /// </summary>
        public static string Propt_FileExistsMessage {
            get {
                return ResourceManager.GetString("Propt_FileExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the Output window pane..
        /// </summary>
        public static string UI_AccessingOutputPaneFailed {
            get {
                return ResourceManager.GetString("UI_AccessingOutputPaneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}    [*ACTIVE*].
        /// </summary>
        public static string UI_ActiveProfileName {
            get {
                return ResourceManager.GetString("UI_ActiveProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ColumnDefinitions.
        /// </summary>
        public static string UI_AddColumnDefinitions {
            get {
                return ResourceManager.GetString("UI_AddColumnDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Keyboard property as {0}.
        /// </summary>
        public static string UI_AddEntryKeyboard {
            get {
                return ResourceManager.GetString("UI_AddEntryKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing column definitions..
        /// </summary>
        public static string UI_AddMissingColumnDefinitions {
            get {
                return ResourceManager.GetString("UI_AddMissingColumnDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing event..
        /// </summary>
        public static string UI_AddMissingEvent {
            get {
                return ResourceManager.GetString("UI_AddMissingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add missing row definitions..
        /// </summary>
        public static string UI_AddMissingRowDefinitions {
            get {
                return ResourceManager.GetString("UI_AddMissingRowDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RowDefinitions and ColumnDefinitions.
        /// </summary>
        public static string UI_AddRowAndColumnDefinitions {
            get {
                return ResourceManager.GetString("UI_AddRowAndColumnDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RowDefinitions.
        /// </summary>
        public static string UI_AddRowDefinitions {
            get {
                return ResourceManager.GetString("UI_AddRowDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify InputScope property..
        /// </summary>
        public static string UI_AddTextBoxInputScope {
            get {
                return ResourceManager.GetString("UI_AddTextBoxInputScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To dependency property.
        /// </summary>
        public static string UI_AnalyzerFixDependencyPropertyTitle {
            get {
                return ResourceManager.GetString("UI_AnalyzerFixDependencyPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To full property that calls `OnPropertyChanged`.
        /// </summary>
        public static string UI_AnalyzerFixOnPropertyChangedTitle {
            get {
                return ResourceManager.GetString("UI_AnalyzerFixOnPropertyChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To full property that calls `SetProperty`.
        /// </summary>
        public static string UI_AnalyzerFixSetPropertyTitle {
            get {
                return ResourceManager.GetString("UI_AnalyzerFixSetPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To full property that calls `Set`.
        /// </summary>
        public static string UI_AnalyzerFixSetTitle {
            get {
                return ResourceManager.GetString("UI_AnalyzerFixSetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalize first letter of Name.
        /// </summary>
        public static string UI_CapitalizeFirstLetterOfName {
            get {
                return ResourceManager.GetString("UI_CapitalizeFirstLetterOfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalize first letter of Uid.
        /// </summary>
        public static string UI_CapitalizeFirstLetterOfUid {
            get {
                return ResourceManager.GetString("UI_CapitalizeFirstLetterOfUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to MediaPlayerElement..
        /// </summary>
        public static string UI_ChangeToMediaPlayerElement {
            get {
                return ResourceManager.GetString("UI_ChangeToMediaPlayerElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (copy).
        /// </summary>
        public static string UI_CopiedProfileName {
            get {
                return ResourceManager.GetString("UI_CopiedProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the Output window pane..
        /// </summary>
        public static string UI_CreatingOutputPaneFailed {
            get {
                return ResourceManager.GetString("UI_CreatingOutputPaneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}    [*FALLBACK*][*ACTIVE*].
        /// </summary>
        public static string UI_FallBackActiveProfileName {
            get {
                return ResourceManager.GetString("UI_FallBackActiveProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}    [*FALLBACK*].
        /// </summary>
        public static string UI_FallBackProfileName {
            get {
                return ResourceManager.GetString("UI_FallBackProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new definition for row {this.tag.RowId}.
        /// </summary>
        public static string UI_InsertNewDefinitionForRow {
            get {
                return ResourceManager.GetString("UI_InsertNewDefinitionForRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move hard-coded string to resource file..
        /// </summary>
        public static string UI_MoveHardCodedString {
            get {
                return ResourceManager.GetString("UI_MoveHardCodedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string UI_NewProfileDefaultName {
            get {
                return ResourceManager.GetString("UI_NewProfileDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- No accessible properties when copying as XAML --&gt;.
        /// </summary>
        public static string UI_NoPropertiesXaml {
            get {
                return ResourceManager.GetString("UI_NoPropertiesXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XAML copied. No profiles configured..
        /// </summary>
        public static string UI_NoXamlCopiedNoProfilesConfigured {
            get {
                return ResourceManager.GetString("UI_NoXamlCopiedNoProfilesConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Profile.
        /// </summary>
        public static string UI_ProfileFilterDescription {
            get {
                return ResourceManager.GetString("UI_ProfileFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Toolkit.
        /// </summary>
        public static string UI_RxtOutputPaneTitle {
            get {
                return ResourceManager.GetString("UI_RxtOutputPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} and {2} other members.
        /// </summary>
        public static string UI_SelectionMoreThanThreeNames {
            get {
                return ResourceManager.GetString("UI_SelectionMoreThanThreeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} and 1 other member.
        /// </summary>
        public static string UI_SelectionThreeNames {
            get {
                return ResourceManager.GetString("UI_SelectionThreeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1}.
        /// </summary>
        public static string UI_SelectionTwoNames {
            get {
                return ResourceManager.GetString("UI_SelectionTwoNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set BindingMode to TwoWay..
        /// </summary>
        public static string UI_SetBindingModeToTwoWay {
            get {
                return ResourceManager.GetString("UI_SetBindingModeToTwoWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML.
        /// </summary>
        public static string UI_ToolboxGroupHeader {
            get {
                return ResourceManager.GetString("UI_ToolboxGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML.
        /// </summary>
        public static string VSCT__ContextMenu {
            get {
                return ResourceManager.GetString("VSCT__ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Clipboard.
        /// </summary>
        public static string VSCT__CopyToClipboardCommandId {
            get {
                return ResourceManager.GetString("VSCT__CopyToClipboardCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create View.
        /// </summary>
        public static string VSCT__CreateViewCommandId {
            get {
                return ResourceManager.GetString("VSCT__CreateViewCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string VSCT__OpenOptionsCommandId {
            get {
                return ResourceManager.GetString("VSCT__OpenOptionsCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Toolbox.
        /// </summary>
        public static string VSCT__SendToToolboxCommandId {
            get {
                return ResourceManager.GetString("VSCT__SendToToolboxCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Datacontext.
        /// </summary>
        public static string VSCT__SetDatacontextCommandId {
            get {
                return ResourceManager.GetString("VSCT__SetDatacontextCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Row Definition.
        /// </summary>
        public static string VSCT_InsertGridRowDefinitionCommandId {
            get {
                return ResourceManager.GetString("VSCT_InsertGridRowDefinitionCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools to accelerate XAML app development.
        /// </summary>
        public static string VSIX__LocalizedDescription {
            get {
                return ResourceManager.GetString("VSIX__LocalizedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Toolkit.
        /// </summary>
        public static string VSIX__LocalizedName {
            get {
                return ResourceManager.GetString("VSIX__LocalizedName", resourceCulture);
            }
        }
    }
}
