//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidXaml.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OptionsStringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionsStringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidXaml.Resources.OptionsStringRes", typeof(OptionsStringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views &amp; ViewModels are in the same project.
        /// </summary>
        public static string Options_AllInOneProject {
            get {
                return ResourceManager.GetString("Options_AllInOneProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate that the ViewModels and Views (XAML files) are in the same project..
        /// </summary>
        public static string Options_AllInOneProjectDescription {
            get {
                return ResourceManager.GetString("Options_AllInOneProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt automatic document formatting.
        /// </summary>
        public static string Options_AttemptAutomaticDocumentFormatting {
            get {
                return ResourceManager.GetString("Options_AttemptAutomaticDocumentFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Visual Studio&apos;s automatic document formatting after modifying a document.
        /// </summary>
        public static string Options_AttemptAutomaticDocumentFormattingDescription {
            get {
                return ResourceManager.GetString("Options_AttemptAutomaticDocumentFormattingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string Options_ButtonAdd {
            get {
                return ResourceManager.GetString("Options_ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string Options_ButtonCopy {
            get {
                return ResourceManager.GetString("Options_ButtonCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string Options_ButtonDelete {
            get {
                return ResourceManager.GetString("Options_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Options_ButtonEdit {
            get {
                return ResourceManager.GetString("Options_ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xport.
        /// </summary>
        public static string Options_ButtonExport {
            get {
                return ResourceManager.GetString("Options_ButtonExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string Options_ButtonImport {
            get {
                return ResourceManager.GetString("Options_ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Options_ButtonNew {
            get {
                return ResourceManager.GetString("Options_ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Options_ButtonOk {
            get {
                return ResourceManager.GetString("Options_ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset.
        /// </summary>
        public static string Options_ButtonReset {
            get {
                return ResourceManager.GetString("Options_ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Set as Active.
        /// </summary>
        public static string Options_ButtonSetAsActive {
            get {
                return ResourceManager.GetString("Options_ButtonSetAsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as _Fall Back.
        /// </summary>
        public static string Options_ButtonSetAsFallBack {
            get {
                return ResourceManager.GetString("Options_ButtonSetAsFallBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class grouping:.
        /// </summary>
        public static string Options_ClassGrouping {
            get {
                return ResourceManager.GetString("Options_ClassGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element that encapsulates the elements created for each property when creating XAML for a class..
        /// </summary>
        public static string Options_ClassGroupingDescription {
            get {
                return ResourceManager.GetString("Options_ClassGroupingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code-behind constructor content:.
        /// </summary>
        public static string Options_CodeBehindConstructorContent {
            get {
                return ResourceManager.GetString("Options_CodeBehindConstructorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code that should be added to the constructor of the code-behind file when setting the datacontext..
        /// </summary>
        public static string Options_CodeBehindConstructorContentDescription {
            get {
                return ResourceManager.GetString("Options_CodeBehindConstructorContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code-behind page content:.
        /// </summary>
        public static string Options_CodeBehindPageContent {
            get {
                return ResourceManager.GetString("Options_CodeBehindPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code that should be added to the code-behind file, outside of the constructor, when setting the datacontext..
        /// </summary>
        public static string Options_CodeBehindPageContentDescription {
            get {
                return ResourceManager.GetString("Options_CodeBehindPageContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code-behind file default content:.
        /// </summary>
        public static string Options_CodeBehindPlaceholder {
            get {
                return ResourceManager.GetString("Options_CodeBehindPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default file contents when creating a code-behind file..
        /// </summary>
        public static string Options_CodeBehindPlaceholderDescription {
            get {
                return ResourceManager.GetString("Options_CodeBehindPlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataContext.
        /// </summary>
        public static string Options_DataContextHeader {
            get {
                return ResourceManager.GetString("Options_DataContextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default code-behind constructor:.
        /// </summary>
        public static string Options_DefaultCodeBehindConstructor {
            get {
                return ResourceManager.GetString("Options_DefaultCodeBehindConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constuctor of the code-behind file that will be added, if needed and one doesn&apos;t already exist..
        /// </summary>
        public static string Options_DefaultCodeBehindConstructorDescription {
            get {
                return ResourceManager.GetString("Options_DefaultCodeBehindConstructorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable extended logging.
        /// </summary>
        public static string Options_EnableExtendedLogging {
            get {
                return ResourceManager.GetString("Options_EnableExtendedLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the amount of information displayed in the output window. Can be helpful in identifying errors or diagnosing why specific output was produced..
        /// </summary>
        public static string Options_EnableExtendedLoggingDescription {
            get {
                return ResourceManager.GetString("Options_EnableExtendedLoggingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum output:.
        /// </summary>
        public static string Options_EnumMappingOutput {
            get {
                return ResourceManager.GetString("Options_EnumMappingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output used for each element of an enumeration..
        /// </summary>
        public static string Options_EnumMappingOutputDescription {
            get {
                return ResourceManager.GetString("Options_EnumMappingOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback output:.
        /// </summary>
        public static string Options_FallbackOutput {
            get {
                return ResourceManager.GetString("Options_FallbackOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output used for a property when no specific mapping can be applied..
        /// </summary>
        public static string Options_FallbackOutputDescription {
            get {
                return ResourceManager.GetString("Options_FallbackOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Options_GeneralHeader {
            get {
                return ResourceManager.GetString("Options_GeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string Options_GeneralSettingsHeader {
            get {
                return ResourceManager.GetString("Options_GeneralSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Profiles and Mappings.
        /// </summary>
        public static string Options_HelpWithProfilesAndMappings {
            get {
                return ResourceManager.GetString("Options_HelpWithProfilesAndMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only if read-only.
        /// </summary>
        public static string Options_MappingIfReadOnly {
            get {
                return ResourceManager.GetString("Options_MappingIfReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mapping should only apply if the property has a public setter..
        /// </summary>
        public static string Options_MappingIfReadOnlyDescription {
            get {
                return ResourceManager.GetString("Options_MappingIfReadOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name filter:.
        /// </summary>
        public static string Options_MappingNameFilter {
            get {
                return ResourceManager.GetString("Options_MappingNameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partial name of the property to match with. Multiple values can be specified if separated by a pipe (|) character..
        /// </summary>
        public static string Options_MappingNameFilterDescription {
            get {
                return ResourceManager.GetString("Options_MappingNameFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        public static string Options_MappingOutput {
            get {
                return ResourceManager.GetString("Options_MappingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output that should be generated if this mapping is used..
        /// </summary>
        public static string Options_MappingOutputDescription {
            get {
                return ResourceManager.GetString("Options_MappingOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappings.
        /// </summary>
        public static string Options_MappingsHeader {
            get {
                return ResourceManager.GetString("Options_MappingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Options_MappingType {
            get {
                return ResourceManager.GetString("Options_MappingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the property to match with. Multiple values can be specified if separated by a pipe (|) character..
        /// </summary>
        public static string Options_MappingTypeDescription {
            get {
                return ResourceManager.GetString("Options_MappingTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming.
        /// </summary>
        public static string Options_NamingHeader {
            get {
                return ResourceManager.GetString("Options_NamingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize solution structure.
        /// </summary>
        public static string Options_NamingVisualizer {
            get {
                return ResourceManager.GetString("Options_NamingVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Options_ProfileName {
            get {
                return ResourceManager.GetString("Options_ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid XAML Toolkit - Edit Profile.
        /// </summary>
        public static string Options_ProfilePageTitle {
            get {
                return ResourceManager.GetString("Options_ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles:.
        /// </summary>
        public static string Options_ProfilesSectionHeader {
            get {
                return ResourceManager.GetString("Options_ProfilesSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure and Naming.
        /// </summary>
        public static string Options_StructureAndNamingHeader {
            get {
                return ResourceManager.GetString("Options_StructureAndNamingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project strucutre.
        /// </summary>
        public static string Options_StrucutreHeader {
            get {
                return ResourceManager.GetString("Options_StrucutreHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-property output:.
        /// </summary>
        public static string Options_SubPropertyOutput {
            get {
                return ResourceManager.GetString("Options_SubPropertyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output used for each property of a generic type..
        /// </summary>
        public static string Options_SubPropertyOutputDescription {
            get {
                return ResourceManager.GetString("Options_SubPropertyOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This UI is temporary and will change before release.
        /// </summary>
        public static string Options_TemporaryUiNotice {
            get {
                return ResourceManager.GetString("Options_TemporaryUiNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel directory name:.
        /// </summary>
        public static string Options_ViewModelDirectoryName {
            get {
                return ResourceManager.GetString("Options_ViewModelDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the folder that contains the ViewModels..
        /// </summary>
        public static string Options_ViewModelDirectoryNameDescription {
            get {
                return ResourceManager.GetString("Options_ViewModelDirectoryNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel file suffix:.
        /// </summary>
        public static string Options_ViewModelFileSuffix {
            get {
                return ResourceManager.GetString("Options_ViewModelFileSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text appended to the end of the name of each ViewModel..
        /// </summary>
        public static string Options_ViewModelFileSuffixDescription {
            get {
                return ResourceManager.GetString("Options_ViewModelFileSuffixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModel project suffix:.
        /// </summary>
        public static string Options_ViewModelProjectSuffix {
            get {
                return ResourceManager.GetString("Options_ViewModelProjectSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text from the end of the name of the project that contains the ViewModels. .
        /// </summary>
        public static string Options_ViewModelProjectSuffixDescription {
            get {
                return ResourceManager.GetString("Options_ViewModelProjectSuffixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid placeholder detected: {0}.
        /// </summary>
        public static string Options_Warn_InvalidPlaceholders {
            get {
                return ResourceManager.GetString("Options_Warn_InvalidPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown placeholder detected: {0}.
        /// </summary>
        public static string Options_Warn_UnknownPlaceholders {
            get {
                return ResourceManager.GetString("Options_Warn_UnknownPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not leave blank. Use &apos;{0}&apos; if no output is required..
        /// </summary>
        public static string Options_Warn_UseNoOutputNotBlank {
            get {
                return ResourceManager.GetString("Options_Warn_UseNoOutputNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Options_XamlAll {
            get {
                return ResourceManager.GetString("Options_XamlAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML Project Type.
        /// </summary>
        public static string Options_XamlDialect {
            get {
                return ResourceManager.GetString("Options_XamlDialect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML file directory name:.
        /// </summary>
        public static string Options_XamlFileDirectoryName {
            get {
                return ResourceManager.GetString("Options_XamlFileDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the folder that contains the Views (XAML files.).
        /// </summary>
        public static string Options_XamlFileDirectoryNameDescription {
            get {
                return ResourceManager.GetString("Options_XamlFileDirectoryNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML file suffix:.
        /// </summary>
        public static string Options_XamlFileSuffix {
            get {
                return ResourceManager.GetString("Options_XamlFileSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text appended to the end of the name of each View (XAML file.).
        /// </summary>
        public static string Options_XamlFileSuffixDescription {
            get {
                return ResourceManager.GetString("Options_XamlFileSuffixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAUI.
        /// </summary>
        public static string Options_XamlMaui {
            get {
                return ResourceManager.GetString("Options_XamlMaui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML page attribute:.
        /// </summary>
        public static string Options_XamlPageAttribute {
            get {
                return ResourceManager.GetString("Options_XamlPageAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute that should be added ot the top level XAMLelement when setting the datacontext..
        /// </summary>
        public static string Options_XamlPageAttributeDescription {
            get {
                return ResourceManager.GetString("Options_XamlPageAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML file default content:.
        /// </summary>
        public static string Options_XamlPlaceholder {
            get {
                return ResourceManager.GetString("Options_XamlPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default file contents when creating a new XAML file..
        /// </summary>
        public static string Options_XamlPlaceholderDescription {
            get {
                return ResourceManager.GetString("Options_XamlPlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML project suffix:.
        /// </summary>
        public static string Options_XamlProjectSuffix {
            get {
                return ResourceManager.GetString("Options_XamlProjectSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text from the end of the name of the project that contains the Views (XAML files.).
        /// </summary>
        public static string Options_XamlProjectSuffixDescription {
            get {
                return ResourceManager.GetString("Options_XamlProjectSuffixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP.
        /// </summary>
        public static string Options_XamlUwp {
            get {
                return ResourceManager.GetString("Options_XamlUwp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinUI.
        /// </summary>
        public static string Options_XamlWinUI {
            get {
                return ResourceManager.GetString("Options_XamlWinUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF.
        /// </summary>
        public static string Options_XamlWpf {
            get {
                return ResourceManager.GetString("Options_XamlWpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin.Forms.
        /// </summary>
        public static string Options_XamlXamarinForms {
            get {
                return ResourceManager.GetString("Options_XamlXamarinForms", resourceCulture);
            }
        }
    }
}
