matrix:
- name: Markdown
  sources:
  - 'docs/*.md'
  default_encoding: utf-8
  aspell:
    lang: en
  dictionary:
    wordlists:
    - config/wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
