// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RapidXaml
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidRapidXamlToolkitPackageString = "ed7fe961-2d10-4598-8040-7423b66b6540";
        public static Guid guidRapidXamlToolkitPackage = new Guid(guidRapidXamlToolkitPackageString);

        public const string guidRapidXamlCommonMenuPackageString = "ed7fe961-2d10-4598-8040-7423b66b6540";
        public static Guid guidRapidXamlCommonMenuPackage = new Guid(guidRapidXamlCommonMenuPackageString);

        public const string guidRapidXamlCommonMenuPackageCmdSetString = "c38bde3a-c557-43e4-bb0a-9f167ace4c10";
        public static Guid guidRapidXamlCommonMenuPackageCmdSet = new Guid(guidRapidXamlCommonMenuPackageCmdSetString);

        public const string GuidVisualStudioXAMLWindowContextMenuString = "4c87b692-1202-46aa-b64c-ef01faec53da";
        public static Guid GuidVisualStudioXAMLWindowContextMenu = new Guid(GuidVisualStudioXAMLWindowContextMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeContextGroup = 0x1100;
        public const int CodeContextMenu = 0x1200;
        public const int XamlContextGroup = 0x2100;
        public const int XamlContextMenu = 0x2200;
        public const int IDVisualStudioXAMLWindowContextMenu = 0x0103;
    }
}