// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RapidXaml
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidRapidXamlToolkitPackageString = "ed7fe961-2d10-4598-8040-7423b66b6540";
        public static Guid guidRapidXamlToolkitPackage = new Guid(guidRapidXamlToolkitPackageString);

        public const string guidRapidXamlCommonMenuPackageString = "ed7fe961-2d10-4598-8040-7423b66b6540";
        public static Guid guidRapidXamlCommonMenuPackage = new Guid(guidRapidXamlCommonMenuPackageString);

        public const string guidRapidXamlCommonMenuPackageCmdSetString = "c38bde3a-c557-43e4-bb0a-9f167ace4c10";
        public static Guid guidRapidXamlCommonMenuPackageCmdSet = new Guid(guidRapidXamlCommonMenuPackageCmdSetString);

        public const string GuidVisualStudioXAMLWindowContextMenuString = "4c87b692-1202-46aa-b64c-ef01faec53da";
        public static Guid GuidVisualStudioXAMLWindowContextMenu = new Guid(GuidVisualStudioXAMLWindowContextMenuString);

        public const string guidRapidXamlAnalysisPackageString = "fd0b0440-83be-4d1b-a449-9ca75d53007c";
        public static Guid guidRapidXamlAnalysisPackage = new Guid(guidRapidXamlAnalysisPackageString);

        public const string guidRapidXamlAnalysisPackageCmdSetString = "f1a4455d-b523-4b08-8ff7-2a964177fcf6";
        public static Guid guidRapidXamlAnalysisPackageCmdSet = new Guid(guidRapidXamlAnalysisPackageCmdSetString);

        public const string guidAnalysisImagesString = "65bebd64-018e-442f-937f-c435cf70f9b8";
        public static Guid guidAnalysisImages = new Guid(guidAnalysisImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeContextGroup = 0x1100;
        public const int CodeContextMenu = 0x1200;
        public const int XamlContextGroup = 0x2100;
        public const int XamlContextMenu = 0x2200;
        public const int IDVisualStudioXAMLWindowContextMenu = 0x0103;
        public const int CodeContextMenuGroup = 0x1300;
        public const int XamlContextMenuGroup = 0x2300;
        public const int XamlContextMenuSecondaryGroup = 0x2400;
        public const int MoveAllHardCodedStringsToResourceFileCommandId = 0x1026;
        public const int FeedbackCommandId = 0x1027;
        public const int AnalyzeCurrentDocCommandId = 0x1028;
        public const int OpenOptionsCommandId = 0x1029;
        public const int bmpCopyAsXaml = 0x0001;
        public const int bmpToolbox = 0x0002;
        public const int bmpCreateView = 0x0003;
        public const int bmpOptions = 0x0004;
        public const int bmpSetDc = 0x0005;
        public const int bmpFeedback = 0x0006;
    }
}