// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RapidXaml
{
    internal sealed partial class Vsix
    {
        public const string Id = "RapidXamlToolkit.0dc8e86a-836b-47e5-aa3f-f5e71c15e37a";
        public const string Name = "Rapid XAML Toolkit";
        public const string Description = @"Tools to accelerate XAML app development.";
        public const string Language = "en-US";
        public const string Version = "0.9.0.5";
        public const string Author = "Matt Lacey";
        public const string Tags = "XAML;UWP;WPF;Xamarin.Forms;Uno;MVVM;MAUI;WinUI;DotNetMaui";
    }
}
