// Copyright (c) Matt Lacey Ltd. All rights reserved.
// Licensed under the MIT license.

using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Windows.Controls;
using System.Windows.Media;
using EnvDTE;
using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.Shell.Interop;

namespace RapidXaml.EditorExtras.SymbolVisualizer
{
    internal sealed class SymbolIconAdornment : TextBlock
    {
        private double? vsFontSize = null;
        private uint? vsPlainTextForeground = null;

        public SymbolIconAdornment(SymbolIconTag tag)
        {
            this.SymbolTag = tag;
            this.Margin = new System.Windows.Thickness(4, 0, 4, 0);
            this.SetTextAndFontFamily(tag);
        }

        public static Dictionary<string, string> KnownSymbols { get; } = new Dictionary<string, string>()
        {
            { "Previous", "\ue100" },
            { "Next", "\ue101" },
            { "Play", "\ue102" },
            { "Pause", "\ue103" },
            { "Edit", "\ue104" },
            { "Save", "\ue105" },
            { "Clear", "\ue106" },
            { "Delete", "\ue107" },
            { "Remove", "\ue108" },
            { "Add", "\ue109" },
            { "Cancel", "\ue10a" },
            { "Accept", "\ue10b" },
            { "More", "\ue10c" },
            { "Redo", "\ue10d" },
            { "Undo", "\ue10e" },
            { "Home", "\ue10f" },
            { "Up", "\ue110" },
            { "Forward", "\ue111" },
            { "Back", "\ue112" },
            { "Favorite", "\ue113" },
            { "Camera", "\ue114" },
            { "Setting", "\ue115" },
            { "Video", "\ue116" },
            { "Sync", "\ue117" },
            { "Download", "\ue118" },
            { "Mail", "\ue119" },
            { "Find", "\ue11a" },
            { "Help", "\ue11b" },
            { "Upload", "\ue11c" },
            { "Emoji", "\ue11d" },
            { "TwoPage", "\ue11e" },
            { "LeaveChat", "\ue11f" },
            { "MailForward", "\ue120" },
            { "Clock", "\ue121" },
            { "Send", "\ue122" },
            { "Crop", "\ue123" },
            { "RotateCamera", "\ue124" },
            { "People", "\ue125" },
            { "OpenPane", "\ue126" },
            { "ClosePane", "\ue127" },
            { "World", "\ue128" },
            { "Flag", "\ue129" },
            { "PreviewLink", "\ue12a" },
            { "Globe", "\ue12b" },
            { "Trim", "\ue12c" },
            { "AttachCamera", "\ue12d" },
            { "ZoomIn", "\ue12e" },
            { "Bookmarks", "\ue12f" },
            { "Document", "\ue130" },
            { "ProtectedDocument", "\ue131" },
            { "Page", "\ue132" },
            { "Bullets", "\ue133" },
            { "Comment", "\ue134" },
            { "MailFilled", "\ue135" },
            { "ContactInfo", "\ue136" },
            { "HangUp", "\ue137" },
            { "ViewAll", "\ue138" },
            { "MapPin", "\ue139" },
            { "Phone", "\ue13a" },
            { "VideoChat", "\ue13b" },
            { "Switch", "\ue13c" },
            { "Contact", "\ue13d" },
            { "Rename", "\ue13e" },
            { "Pin", "\ue141" },
            { "MusicInfo", "\ue142" },
            { "Go", "\ue143" },
            { "Keyboard", "\ue144" },
            { "DockLeft", "\ue145" },
            { "DockRight", "\ue146" },
            { "DockBottom", "\ue147" },
            { "Remote", "\ue148" },
            { "Refresh", "\ue149" },
            { "Rotate", "\ue14a" },
            { "Shuffle", "\ue14b" },
            { "List", "\ue14c" },
            { "Shop", "\ue14d" },
            { "SelectAll", "\ue14e" },
            { "Orientation", "\ue14f" },
            { "Import", "\ue150" },
            { "ImportAll", "\ue151" },
            { "BrowsePhotos", "\ue155" },
            { "WebCam", "\ue156" },
            { "Pictures", "\ue158" },
            { "SaveLocal", "\ue159" },
            { "Caption", "\ue15a" },
            { "Stop", "\ue15b" },
            { "ShowResults", "\ue15c" },
            { "Volume", "\ue15d" },
            { "Repair", "\ue15e" },
            { "Message", "\ue15f" },
            { "Page2", "\ue160" },
            { "CalendarDay", "\ue161" },
            { "CalendarWeek", "\ue162" },
            { "Calendar", "\ue163" },
            { "Character", "\ue164" },
            { "MailReplyAll", "\ue165" },
            { "Read", "\ue166" },
            { "Link", "\ue167" },
            { "Account", "\ue168" },
            { "ShowBCC", "\ue169" },
            { "HideBCC", "\ue16a" },
            { "Cut", "\ue16b" },
            { "Attach", "\ue16c" },
            { "Paste", "\ue16d" },
            { "Filter", "\ue16e" },
            { "Copy", "\ue16f" },
            { "Emoji2", "\ue170" },
            { "Important", "\ue171" },
            { "MailReply", "\ue172" },
            { "SlideShow", "\ue173" },
            { "Sort", "\ue174" },
            { "Manage", "\ue178" },
            { "AllApps", "\ue179" },
            { "DisconnectDrive", "\ue17a" },
            { "MapDrive", "\ue17b" },
            { "NewWindow", "\ue17c" },
            { "OpenWith", "\ue17d" },
            { "ContactPresence", "\ue181" },
            { "Priority", "\ue182" },
            { "GoToToday", "\ue184" },
            { "Font", "\ue185" },
            { "FontColor", "\ue186" },
            { "Contact2", "\ue187" },
            { "Folder", "\ue188" },
            { "Audio", "\ue189" },
            { "Placeholder", "\ue18a" },
            { "View", "\ue18b" },
            { "SetLockScreen", "\ue18c" },
            { "SetTile", "\ue18d" },
            { "ClosedCaption", "\ue190" },
            { "StopSlideShow", "\ue191" },
            { "Permissions", "\ue192" },
            { "Highlight", "\ue193" },
            { "DisableUpdates", "\ue194" },
            { "Unfavorite", "\ue195" },
            { "UnPin", "\ue196" },
            { "OpenLocal", "\ue197" },
            { "Mute", "\ue198" },
            { "Italic", "\ue199" },
            { "Underline", "\ue19a" },
            { "Bold", "\ue19b" },
            { "MoveToFolder", "\ue19c" },
            { "LikeDislike", "\ue19d" },
            { "Dislike", "\ue19e" },
            { "Like", "\ue19f" },
            { "AlignRight", "\ue1a0" },
            { "AlignCenter", "\ue1a1" },
            { "AlignLeft", "\ue1a2" },
            { "Zoom", "\ue1a3" },
            { "ZoomOut", "\ue1a4" },
            { "OpenFile", "\ue1a5" },
            { "OtherUser", "\ue1a6" },
            { "Admin", "\ue1a7" },
            { "Street", "\ue1c3" },
            { "Map", "\ue1c4" },
            { "ClearSelection", "\ue1c5" },
            { "FontDecrease", "\ue1c6" },
            { "FontIncrease", "\ue1c7" },
            { "FontSize", "\ue1c8" },
            { "CellPhone", "\ue1c9" },
            { "Reshare", "\ue1ca" },
            { "Tag", "\ue1cb" },
            { "Repeat1", "\ue1cc" },
            { "RepeatAll", "\ue1cd" },
            { "OutlineStar", "\ue1ce" },
            { "SolidStar", "\ue1cf" },
            { "Calculator", "\ue1d0" },
            { "Directions", "\ue1d1" },
            { "Target", "\ue1d2" },
            { "Library", "\ue1d3" },
            { "PhoneBook", "\ue1d4" },
            { "Memo", "\ue1d5" },
            { "Microphone", "\ue1d6" },
            { "PostUpdate", "\ue1d7" },
            { "BackToWindow", "\ue1d8" },
            { "FullScreen", "\ue1d9" },
            { "NewFolder", "\ue1da" },
            { "CalendarReply", "\ue1db" },
            { "UnsyncFolder", "\ue1dd" },
            { "ReportHacked", "\ue1de" },
            { "SyncFolder", "\ue1df" },
            { "BlockContact", "\ue1e0" },
            { "SwitchApps", "\ue1e1" },
            { "AddFriend", "\ue1e2" },
            { "TouchPointer", "\ue1e3" },
            { "GoToStart", "\ue1e4" },
            { "ZeroBars", "\ue1e5" },
            { "OneBar", "\ue1e6" },
            { "TwoBars", "\ue1e7" },
            { "ThreeBars", "\ue1e8" },
            { "FourBars", "\ue1e9" },
            { "Scan", "\ue294" },
            { "Preview", "\ue295" },
            { "GlobalNav", "\ue700" },
            { "Share", "\ue72d" },
            { "Print", "\ue749" },
            { "Xbox", "\ue990" },
        };

        public static Dictionary<string, string> KnownFontAwesomeIcons { get; } = new Dictionary<string, string>()
        {
            { "_500Px ", "\uf26e" },
            { "AddressBook", "\uf2b9" },
            { "AddressBookOutline", "\uf2ba" },
            { "AddressCard", "\uf2bb" },
            { "AddressCardOutline", "\uf2bc" },
            { "Adjust", "\uf042" },
            { "Adn", "\uf170" },
            { "AlignCenter", "\uf037" },
            { "AlignJustify", "\uf039" },
            { "AlignLeft", "\uf036" },
            { "AlignRight", "\uf038" },
            { "Amazon", "\uf270" },
            { "Ambulance", "\uf0f9" },
            { "AmericanSignLanguageInterpreting", "\uf2a3" },
            { "Anchor", "\uf13d" },
            { "Android", "\uf17b" },
            { "Angellist", "\uf209" },
            { "AngleDoubleDown", "\uf103" },
            { "AngleDoubleLeft", "\uf100" },
            { "AngleDoubleRight", "\uf101" },
            { "AngleDoubleUp", "\uf102" },
            { "AngleDown", "\uf107" },
            { "AngleLeft", "\uf104" },
            { "AngleRight", "\uf105" },
            { "AngleUp", "\uf106" },
            { "Apple", "\uf179" },
            { "Archive", "\uf187" },
            { "AreaChart", "\uf1fe" },
            { "ArrowCircleDown", "\uf0ab" },
            { "ArrowCircleLeft", "\uf0a8" },
            { "ArrowCircleOutlineDown", "\uf01a" },
            { "ArrowCircleOutlineLeft", "\uf190" },
            { "ArrowCircleOutlineRight", "\uf18e" },
            { "ArrowCircleOutlineUp", "\uf01b" },
            { "ArrowCircleRight", "\uf0a9" },
            { "ArrowCircleUp", "\uf0aa" },
            { "ArrowDown", "\uf063" },
            { "ArrowLeft", "\uf060" },
            { "ArrowRight", "\uf061" },
            { "Arrows", "\uf047" },
            { "ArrowsAlt", "\uf0b2" },
            { "ArrowsH", "\uf07e" },
            { "ArrowsV", "\uf07d" },
            { "ArrowUp", "\uf062" },
            { "AslInterpreting", "\uf2a3" },
            { "AssistiveListeningSystems", "\uf2a2" },
            { "Asterisk", "\uf069" },
            { "At", "\uf1fa" },
            { "AudioDescription", "\uf29e" },
            { "Automobile", "\uf1b9" },
            { "Backward", "\uf04a" },
            { "BalanceScale", "\uf24e" },
            { "Ban", "\uf05e" },
            { "Bandcamp", "\uf2d5" },
            { "Bank", "\uf19c" },
            { "BarChart", "\uf080" },
            { "BarChartOutline", "\uf080" },
            { "Barcode", "\uf02a" },
            { "Bars", "\uf0c9" },
            { "Bath", "\uf2cd" },
            { "Bathtub", "\uf2cd" },
            { "Battery", "\uf240" },
            { "Battery0", "\uf244" },
            { "Battery1", "\uf243" },
            { "Battery2", "\uf242" },
            { "Battery3", "\uf241" },
            { "Battery4", "\uf240" },
            { "BatteryEmpty", "\uf244" },
            { "BatteryFull", "\uf240" },
            { "BatteryHalf", "\uf242" },
            { "BatteryQuarter", "\uf243" },
            { "BatteryThreeQuarters", "\uf241" },
            { "Bed", "\uf236" },
            { "Beer", "\uf0fc" },
            { "Behance", "\uf1b4" },
            { "BehanceSquare", "\uf1b5" },
            { "Bell", "\uf0f3" },
            { "BellOutline", "\uf0a2" },
            { "BellSlash", "\uf1f6" },
            { "BellSlashOutline", "\uf1f7" },
            { "Bicycle", "\uf206" },
            { "Binoculars", "\uf1e5" },
            { "BirthdayCake", "\uf1fd" },
            { "Bitbucket", "\uf171" },
            { "BitbucketSquare", "\uf172" },
            { "Bitcoin", "\uf15a" },
            { "BlackTie", "\uf27e" },
            { "Blind", "\uf29d" },
            { "Bluetooth", "\uf293" },
            { "BluetoothB", "\uf294" },
            { "Bold", "\uf032" },
            { "Bolt", "\uf0e7" },
            { "Bomb", "\uf1e2" },
            { "Book", "\uf02d" },
            { "Bookmark", "\uf02e" },
            { "BookmarkOutline", "\uf097" },
            { "Braille", "\uf2a1" },
            { "Briefcase", "\uf0b1" },
            { "Btc", "\uf15a" },
            { "Bug", "\uf188" },
            { "Building", "\uf1ad" },
            { "BuildingOutline", "\uf0f7" },
            { "Bullhorn", "\uf0a1" },
            { "Bullseye", "\uf140" },
            { "Bus", "\uf207" },
            { "Buysellads", "\uf20d" },
            { "Cab", "\uf1ba" },
            { "Calculator", "\uf1ec" },
            { "Calendar", "\uf073" },
            { "CalendarCheckOutline", "\uf274" },
            { "CalendarMinusOutline", "\uf272" },
            { "CalendarOutline", "\uf133" },
            { "CalendarPlusOutline", "\uf271" },
            { "CalendarTimesOutline", "\uf273" },
            { "Camera", "\uf030" },
            { "CameraRetro", "\uf083" },
            { "Car", "\uf1b9" },
            { "CaretDown", "\uf0d7" },
            { "CaretLeft", "\uf0d9" },
            { "CaretRight", "\uf0da" },
            { "CaretSquareOutlineDown", "\uf150" },
            { "CaretSquareOutlineLeft", "\uf191" },
            { "CaretSquareOutlineRight", "\uf152" },
            { "CaretSquareOutlineUp", "\uf151" },
            { "CaretUp", "\uf0d8" },
            { "CartArrowDown", "\uf218" },
            { "CartPlus", "\uf217" },
            { "Cc", "\uf20a" },
            { "CcAmex", "\uf1f3" },
            { "CcDinersClub", "\uf24c" },
            { "CcDiscover", "\uf1f2" },
            { "CcJcb", "\uf24b" },
            { "CcMastercard", "\uf1f1" },
            { "CcPaypal", "\uf1f4" },
            { "CcStripe", "\uf1f5" },
            { "CcVisa", "\uf1f0" },
            { "Certificate", "\uf0a3" },
            { "Chain", "\uf0c1" },
            { "ChainBroken", "\uf127" },
            { "Check", "\uf00c" },
            { "CheckCircle", "\uf058" },
            { "CheckCircleOutline", "\uf05d" },
            { "CheckSquare", "\uf14a" },
            { "CheckSquareOutline", "\uf046" },
            { "ChevronCircleDown", "\uf13a" },
            { "ChevronCircleLeft", "\uf137" },
            { "ChevronCircleRight", "\uf138" },
            { "ChevronCircleUp", "\uf139" },
            { "ChevronDown", "\uf078" },
            { "ChevronLeft", "\uf053" },
            { "ChevronRight", "\uf054" },
            { "ChevronUp", "\uf077" },
            { "Child", "\uf1ae" },
            { "Chrome", "\uf268" },
            { "Circle", "\uf111" },
            { "CircleOutline", "\uf10c" },
            { "CircleOutlineNotch", "\uf1ce" },
            { "CircleThin", "\uf1db" },
            { "Clipboard", "\uf0ea" },
            { "ClockOutline", "\uf017" },
            { "Clone", "\uf24d" },
            { "Close", "\uf00d" },
            { "Cloud", "\uf0c2" },
            { "CloudDownload", "\uf0ed" },
            { "CloudUpload", "\uf0ee" },
            { "Cny", "\uf157" },
            { "Code", "\uf121" },
            { "CodeFork", "\uf126" },
            { "Codepen", "\uf1cb" },
            { "Codiepie", "\uf284" },
            { "Coffee", "\uf0f4" },
            { "Cog", "\uf013" },
            { "Cogs", "\uf085" },
            { "Columns", "\uf0db" },
            { "Comment", "\uf075" },
            { "Commenting", "\uf27a" },
            { "CommentingOutline", "\uf27b" },
            { "CommentOutline", "\uf0e5" },
            { "Comments", "\uf086" },
            { "CommentsOutline", "\uf0e6" },
            { "Compass", "\uf14e" },
            { "Compress", "\uf066" },
            { "Connectdevelop", "\uf20e" },
            { "Contao", "\uf26d" },
            { "Copy", "\uf0c5" },
            { "Copyright", "\uf1f9" },
            { "CreativeCommons", "\uf25e" },
            { "CreditCard", "\uf09d" },
            { "CreditCardAlt", "\uf283" },
            { "Crop", "\uf125" },
            { "Crosshairs", "\uf05b" },
            { "Css3", "\uf13c" },
            { "Cube", "\uf1b2" },
            { "Cubes", "\uf1b3" },
            { "Cut", "\uf0c4" },
            { "Cutlery", "\uf0f5" },
            { "Dashboard", "\uf0e4" },
            { "Dashcube", "\uf210" },
            { "Database", "\uf1c0" },
            { "Deaf", "\uf2a4" },
            { "Deafness", "\uf2a4" },
            { "Dedent", "\uf03b" },
            { "Delicious", "\uf1a5" },
            { "Desktop", "\uf108" },
            { "Deviantart", "\uf1bd" },
            { "Diamond", "\uf219" },
            { "Digg", "\uf1a6" },
            { "Dollar", "\uf155" },
            { "DotCircleOutline", "\uf192" },
            { "Download", "\uf019" },
            { "Dribbble", "\uf17d" },
            { "DriversLicense", "\uf2c2" },
            { "DriversLicenseOutline", "\uf2c3" },
            { "Dropbox", "\uf16b" },
            { "Drupal", "\uf1a9" },
            { "Edge", "\uf282" },
            { "Edit", "\uf044" },
            { "Eercast", "\uf2da" },
            { "Eject", "\uf052" },
            { "EllipsisH", "\uf141" },
            { "EllipsisV", "\uf142" },
            { "Empire", "\uf1d1" },
            { "Envelope", "\uf0e0" },
            { "EnvelopeOpen", "\uf2b6" },
            { "EnvelopeOutline", "\uf003" },
            { "EnvelopeOutlinepenOutline", "\uf2b7" },
            { "EnvelopeSquare", "\uf199" },
            { "Envira", "\uf299" },
            { "Eraser", "\uf12d" },
            { "Etsy", "\uf2d7" },
            { "Eur", "\uf153" },
            { "Euro", "\uf153" },
            { "Exchange", "\uf0ec" },
            { "Exclamation", "\uf12a" },
            { "ExclamationCircle", "\uf06a" },
            { "ExclamationTriangle", "\uf071" },
            { "Expand", "\uf065" },
            { "Expeditedssl", "\uf23e" },
            { "ExternalLink", "\uf08e" },
            { "ExternalLinkSquare", "\uf14c" },
            { "Eye", "\uf06e" },
            { "Eyedropper", "\uf1fb" },
            { "EyeSlash", "\uf070" },
            { "Fa", "\uf2b4" },
            { "Facebook", "\uf09a" },
            { "FacebookF", "\uf09a" },
            { "FacebookOfficial", "\uf230" },
            { "FacebookSquare", "\uf082" },
            { "FastBackward", "\uf049" },
            { "FastForward", "\uf050" },
            { "Fax", "\uf1ac" },
            { "Feed", "\uf09e" },
            { "Female", "\uf182" },
            { "FighterJet", "\uf0fb" },
            { "File", "\uf15b" },
            { "FileArchiveOutline", "\uf1c6" },
            { "FileAudioOutline", "\uf1c7" },
            { "FileCodeOutline", "\uf1c9" },
            { "FileExcelOutline", "\uf1c3" },
            { "FileImageOutline", "\uf1c5" },
            { "FileMovieOutline", "\uf1c8" },
            { "FileOutline", "\uf016" },
            { "FilePdfOutline", "\uf1c1" },
            { "FilePhotoOutline", "\uf1c5" },
            { "FilePictureOutline", "\uf1c5" },
            { "FilePowerpointOutline", "\uf1c4" },
            { "FileSoundOutline", "\uf1c7" },
            { "FilesOutline", "\uf0c5" },
            { "FileText", "\uf15c" },
            { "FileTextOutline", "\uf0f6" },
            { "FileVideoOutline", "\uf1c8" },
            { "FileWordOutline", "\uf1c2" },
            { "FileZipOutline", "\uf1c6" },
            { "Film", "\uf008" },
            { "Filter", "\uf0b0" },
            { "Fire", "\uf06d" },
            { "FireExtinguisher", "\uf134" },
            { "Firefox", "\uf269" },
            { "FirstOrder", "\uf2b0" },
            { "Flag", "\uf024" },
            { "FlagCheckered", "\uf11e" },
            { "FlagOutline", "\uf11d" },
            { "Flash", "\uf0e7" },
            { "Flask", "\uf0c3" },
            { "Flickr", "\uf16e" },
            { "FloppyOutline", "\uf0c7" },
            { "Folder", "\uf07b" },
            { "FolderOpen", "\uf07c" },
            { "FolderOutline", "\uf114" },
            { "FolderOutlinepenOutline", "\uf115" },
            { "Font", "\uf031" },
            { "FontAwesome", "\uf2b4" },
            { "Fonticons", "\uf280" },
            { "FortAwesome", "\uf286" },
            { "Forumbee", "\uf211" },
            { "Forward", "\uf04e" },
            { "Foursquare", "\uf180" },
            { "FreeCodeCamp", "\uf2c5" },
            { "FrownOutline", "\uf119" },
            { "FutbolOutline", "\uf1e3" },
            { "Gamepad", "\uf11b" },
            { "Gavel", "\uf0e3" },
            { "Gbp", "\uf154" },
            { "Ge", "\uf1d1" },
            { "Gear", "\uf013" },
            { "Gears", "\uf085" },
            { "Genderless", "\uf22d" },
            { "GetPocket", "\uf265" },
            { "Gg", "\uf260" },
            { "GgCircle", "\uf261" },
            { "Gift", "\uf06b" },
            { "Git", "\uf1d3" },
            { "Github", "\uf09b" },
            { "GithubAlt", "\uf113" },
            { "GithubSquare", "\uf092" },
            { "Gitlab", "\uf296" },
            { "GitSquare", "\uf1d2" },
            { "Gittip", "\uf184" },
            { "Glass", "\uf000" },
            { "Glide", "\uf2a5" },
            { "GlideG", "\uf2a6" },
            { "Globe", "\uf0ac" },
            { "Google", "\uf1a0" },
            { "GooglePlus", "\uf0d5" },
            { "GooglePlusCircle", "\uf2b3" },
            { "GooglePlusOfficial", "\uf2b3" },
            { "GooglePlusSquare", "\uf0d4" },
            { "GoogleWallet", "\uf1ee" },
            { "GraduationCap", "\uf19d" },
            { "Gratipay", "\uf184" },
            { "Grav", "\uf2d6" },
            { "Group", "\uf0c0" },
            { "HackerNews", "\uf1d4" },
            { "HandGrabOutline", "\uf255" },
            { "HandLizardOutline", "\uf258" },
            { "HandOutlineDown", "\uf0a7" },
            { "HandOutlineLeft", "\uf0a5" },
            { "HandOutlineRight", "\uf0a4" },
            { "HandOutlineUp", "\uf0a6" },
            { "HandPaperOutline", "\uf256" },
            { "HandPeaceOutline", "\uf25b" },
            { "HandPointerOutline", "\uf25a" },
            { "HandRockOutline", "\uf255" },
            { "HandScissorsOutline", "\uf257" },
            { "HandshakeOutline", "\uf2b5" },
            { "HandSpockOutline", "\uf259" },
            { "HandStopOutline", "\uf256" },
            { "HardOfHearing", "\uf2a4" },
            { "Hashtag", "\uf292" },
            { "HddOutline", "\uf0a0" },
            { "Header", "\uf1dc" },
            { "Headphones", "\uf025" },
            { "Heart", "\uf004" },
            { "Heartbeat", "\uf21e" },
            { "HeartOutline", "\uf08a" },
            { "History", "\uf1da" },
            { "Home", "\uf015" },
            { "HospitalOutline", "\uf0f8" },
            { "Hotel", "\uf236" },
            { "Hourglass", "\uf254" },
            { "Hourglass1", "\uf251" },
            { "Hourglass2", "\uf252" },
            { "Hourglass3", "\uf253" },
            { "HourglassEnd", "\uf253" },
            { "HourglassHalf", "\uf252" },
            { "HourglassOutline", "\uf250" },
            { "HourglassStart", "\uf251" },
            { "Houzz", "\uf27c" },
            { "HSquare", "\uf0fd" },
            { "Html5", "\uf13b" },
            { "ICursor", "\uf246" },
            { "IdBadge", "\uf2c1" },
            { "IdCard", "\uf2c2" },
            { "IdCardOutline", "\uf2c3" },
            { "Ils", "\uf20b" },
            { "Image", "\uf03e" },
            { "Imdb", "\uf2d8" },
            { "Inbox", "\uf01c" },
            { "Indent", "\uf03c" },
            { "Industry", "\uf275" },
            { "Info", "\uf129" },
            { "InfoCircle", "\uf05a" },
            { "Inr", "\uf156" },
            { "Instagram", "\uf16d" },
            { "Institution", "\uf19c" },
            { "InternetExplorer", "\uf26b" },
            { "Intersex", "\uf224" },
            { "Ioxhost", "\uf208" },
            { "Italic", "\uf033" },
            { "Joomla", "\uf1aa" },
            { "Jpy", "\uf157" },
            { "Jsfiddle", "\uf1cc" },
            { "Key", "\uf084" },
            { "KeyboardOutline", "\uf11c" },
            { "Krw", "\uf159" },
            { "Language", "\uf1ab" },
            { "Laptop", "\uf109" },
            { "Lastfm", "\uf202" },
            { "LastfmSquare", "\uf203" },
            { "Leaf", "\uf06c" },
            { "Leanpub", "\uf212" },
            { "Legal", "\uf0e3" },
            { "LemonOutline", "\uf094" },
            { "LevelDown", "\uf149" },
            { "LevelUp", "\uf148" },
            { "LifeBouy", "\uf1cd" },
            { "LifeBuoy", "\uf1cd" },
            { "LifeRing", "\uf1cd" },
            { "LifeSaver", "\uf1cd" },
            { "LightbulbOutline", "\uf0eb" },
            { "LineChart", "\uf201" },
            { "Link", "\uf0c1" },
            { "Linkedin", "\uf0e1" },
            { "LinkedinSquare", "\uf08c" },
            { "Linode", "\uf2b8" },
            { "Linux", "\uf17c" },
            { "List", "\uf03a" },
            { "ListAlt", "\uf022" },
            { "ListOl", "\uf0cb" },
            { "ListUl", "\uf0ca" },
            { "LocationArrow", "\uf124" },
            { "Lock", "\uf023" },
            { "LongArrowDown", "\uf175" },
            { "LongArrowLeft", "\uf177" },
            { "LongArrowRight", "\uf178" },
            { "LongArrowUp", "\uf176" },
            { "LowVision", "\uf2a8" },
            { "Magic", "\uf0d0" },
            { "Magnet", "\uf076" },
            { "MailForward", "\uf064" },
            { "MailReply", "\uf112" },
            { "MailReplyAll", "\uf122" },
            { "Male", "\uf183" },
            { "Map", "\uf279" },
            { "MapMarker", "\uf041" },
            { "MapOutline", "\uf278" },
            { "MapPin", "\uf276" },
            { "MapSigns", "\uf277" },
            { "Mars", "\uf222" },
            { "MarsDouble", "\uf227" },
            { "MarsStroke", "\uf229" },
            { "MarsStrokeH", "\uf22b" },
            { "MarsStrokeV", "\uf22a" },
            { "Maxcdn", "\uf136" },
            { "Meanpath", "\uf20c" },
            { "Medium", "\uf23a" },
            { "Medkit", "\uf0fa" },
            { "Meetup", "\uf2e0" },
            { "MehOutline", "\uf11a" },
            { "Mercury", "\uf223" },
            { "Microchip", "\uf2db" },
            { "Microphone", "\uf130" },
            { "MicrophoneSlash", "\uf131" },
            { "Minus", "\uf068" },
            { "MinusCircle", "\uf056" },
            { "MinusSquare", "\uf146" },
            { "MinusSquareOutline", "\uf147" },
            { "Mixcloud", "\uf289" },
            { "Mobile", "\uf10b" },
            { "MobilePhone", "\uf10b" },
            { "Modx", "\uf285" },
            { "Money", "\uf0d6" },
            { "MoonOutline", "\uf186" },
            { "MortarBoard", "\uf19d" },
            { "Motorcycle", "\uf21c" },
            { "MousePointer", "\uf245" },
            { "Music", "\uf001" },
            { "Navicon", "\uf0c9" },
            { "Neuter", "\uf22c" },
            { "NewspaperOutline", "\uf1ea" },
            { "ObjectGroup", "\uf247" },
            { "ObjectUngroup", "\uf248" },
            { "Odnoklassniki", "\uf263" },
            { "OdnoklassnikiSquare", "\uf264" },
            { "Opencart", "\uf23d" },
            { "Openid", "\uf19b" },
            { "Opera", "\uf26a" },
            { "OptinMonster", "\uf23c" },
            { "Outdent", "\uf03b" },
            { "Pagelines", "\uf18c" },
            { "PaintBrush", "\uf1fc" },
            { "Paperclip", "\uf0c6" },
            { "PaperPlane", "\uf1d8" },
            { "PaperPlaneOutline", "\uf1d9" },
            { "Paragraph", "\uf1dd" },
            { "Paste", "\uf0ea" },
            { "Pause", "\uf04c" },
            { "PauseCircle", "\uf28b" },
            { "PauseCircleOutline", "\uf28c" },
            { "Paw", "\uf1b0" },
            { "Paypal", "\uf1ed" },
            { "Pencil", "\uf040" },
            { "PencilSquare", "\uf14b" },
            { "PencilSquareOutline", "\uf044" },
            { "Percent", "\uf295" },
            { "Phone", "\uf095" },
            { "PhoneSquare", "\uf098" },
            { "Photo", "\uf03e" },
            { "PictureOutline", "\uf03e" },
            { "PieChart", "\uf200" },
            { "PiedPiper", "\uf2ae" },
            { "PiedPiperAlt", "\uf1a8" },
            { "PiedPiperPp", "\uf1a7" },
            { "Pinterest", "\uf0d2" },
            { "PinterestP", "\uf231" },
            { "PinterestSquare", "\uf0d3" },
            { "Plane", "\uf072" },
            { "Play", "\uf04b" },
            { "PlayCircle", "\uf144" },
            { "PlayCircleOutline", "\uf01d" },
            { "Plug", "\uf1e6" },
            { "Plus", "\uf067" },
            { "PlusCircle", "\uf055" },
            { "PlusSquare", "\uf0fe" },
            { "PlusSquareOutline", "\uf196" },
            { "Podcast", "\uf2ce" },
            { "PowerOff", "\uf011" },
            { "Print", "\uf02f" },
            { "ProductHunt", "\uf288" },
            { "PuzzlePiece", "\uf12e" },
            { "Qq", "\uf1d6" },
            { "Qrcode", "\uf029" },
            { "Question", "\uf128" },
            { "QuestionCircle", "\uf059" },
            { "QuestionCircleOutline", "\uf29c" },
            { "Quora", "\uf2c4" },
            { "QuoteLeft", "\uf10d" },
            { "QuoteRight", "\uf10e" },
            { "Ra", "\uf1d0" },
            { "Random", "\uf074" },
            { "Ravelry", "\uf2d9" },
            { "Rebel", "\uf1d0" },
            { "Recycle", "\uf1b8" },
            { "Reddit", "\uf1a1" },
            { "RedditAlien", "\uf281" },
            { "RedditSquare", "\uf1a2" },
            { "Refresh", "\uf021" },
            { "Registered", "\uf25d" },
            { "Remove", "\uf00d" },
            { "Renren", "\uf18b" },
            { "Reorder", "\uf0c9" },
            { "Repeat", "\uf01e" },
            { "Reply", "\uf112" },
            { "ReplyAll", "\uf122" },
            { "Resistance", "\uf1d0" },
            { "Retweet", "\uf079" },
            { "Rmb", "\uf157" },
            { "Road", "\uf018" },
            { "Rocket", "\uf135" },
            { "RotateLeft", "\uf0e2" },
            { "RotateRight", "\uf01e" },
            { "Rouble", "\uf158" },
            { "Rss", "\uf09e" },
            { "RssSquare", "\uf143" },
            { "Rub", "\uf158" },
            { "Ruble", "\uf158" },
            { "Rupee", "\uf156" },
            { "S15", "\uf2cd" },
            { "Safari", "\uf267" },
            { "Save", "\uf0c7" },
            { "Scissors", "\uf0c4" },
            { "Scribd", "\uf28a" },
            { "Search", "\uf002" },
            { "SearchMinus", "\uf010" },
            { "SearchPlus", "\uf00e" },
            { "Sellsy", "\uf213" },
            { "Send", "\uf1d8" },
            { "SendOutline", "\uf1d9" },
            { "Server", "\uf233" },
            { "Share", "\uf064" },
            { "ShareAlt", "\uf1e0" },
            { "ShareAltSquare", "\uf1e1" },
            { "ShareSquare", "\uf14d" },
            { "ShareSquareOutline", "\uf045" },
            { "Shekel", "\uf20b" },
            { "Sheqel", "\uf20b" },
            { "Shield", "\uf132" },
            { "Ship", "\uf21a" },
            { "Shirtsinbulk", "\uf214" },
            { "ShoppingBag", "\uf290" },
            { "ShoppingBasket", "\uf291" },
            { "ShoppingCart", "\uf07a" },
            { "Shower", "\uf2cc" },
            { "Signal", "\uf012" },
            { "SignIn", "\uf090" },
            { "Signing", "\uf2a7" },
            { "SignLanguage", "\uf2a7" },
            { "SignOut", "\uf08b" },
            { "Simplybuilt", "\uf215" },
            { "Sitemap", "\uf0e8" },
            { "Skyatlas", "\uf216" },
            { "Skype", "\uf17e" },
            { "Slack", "\uf198" },
            { "Sliders", "\uf1de" },
            { "Slideshare", "\uf1e7" },
            { "SmileOutline", "\uf118" },
            { "Snapchat", "\uf2ab" },
            { "SnapchatGhost", "\uf2ac" },
            { "SnapchatSquare", "\uf2ad" },
            { "SnowflakeOutline", "\uf2dc" },
            { "SoccerBallOutline", "\uf1e3" },
            { "Sort", "\uf0dc" },
            { "SortAlphaAsc", "\uf15d" },
            { "SortAlphaDesc", "\uf15e" },
            { "SortAmountAsc", "\uf160" },
            { "SortAmountDesc", "\uf161" },
            { "SortAsc", "\uf0de" },
            { "SortDesc", "\uf0dd" },
            { "SortDown", "\uf0dd" },
            { "SortNumericAsc", "\uf162" },
            { "SortNumericDesc", "\uf163" },
            { "SortUp", "\uf0de" },
            { "Soundcloud", "\uf1be" },
            { "SpaceShuttle", "\uf197" },
            { "Spinner", "\uf110" },
            { "Spoon", "\uf1b1" },
            { "Spotify", "\uf1bc" },
            { "Square", "\uf0c8" },
            { "SquareOutline", "\uf096" },
            { "StackExchange", "\uf18d" },
            { "StackOverflow", "\uf16c" },
            { "Star", "\uf005" },
            { "StarHalf", "\uf089" },
            { "StarHalfEmpty", "\uf123" },
            { "StarHalfFull", "\uf123" },
            { "StarHalfOutline", "\uf123" },
            { "StarOutline", "\uf006" },
            { "Steam", "\uf1b6" },
            { "SteamSquare", "\uf1b7" },
            { "StepBackward", "\uf048" },
            { "StepForward", "\uf051" },
            { "Stethoscope", "\uf0f1" },
            { "StickyNote", "\uf249" },
            { "StickyNoteOutline", "\uf24a" },
            { "Stop", "\uf04d" },
            { "StopCircle", "\uf28d" },
            { "StopCircleOutline", "\uf28e" },
            { "StreetView", "\uf21d" },
            { "Strikethrough", "\uf0cc" },
            { "Stumbleupon", "\uf1a4" },
            { "StumbleuponCircle", "\uf1a3" },
            { "Subscript", "\uf12c" },
            { "Subway", "\uf239" },
            { "Suitcase", "\uf0f2" },
            { "SunOutline", "\uf185" },
            { "Superpowers", "\uf2dd" },
            { "Superscript", "\uf12b" },
            { "Support", "\uf1cd" },
            { "Table", "\uf0ce" },
            { "Tablet", "\uf10a" },
            { "Tachometer", "\uf0e4" },
            { "Tag", "\uf02b" },
            { "Tags", "\uf02c" },
            { "Tasks", "\uf0ae" },
            { "Taxi", "\uf1ba" },
            { "Telegram", "\uf2c6" },
            { "Television", "\uf26c" },
            { "TencentWeibo", "\uf1d5" },
            { "Terminal", "\uf120" },
            { "TextHeight", "\uf034" },
            { "TextWidth", "\uf035" },
            { "Th", "\uf00a" },
            { "Themeisle", "\uf2b2" },
            { "Thermometer", "\uf2c7" },
            { "Thermometer0", "\uf2cb" },
            { "Thermometer1", "\uf2ca" },
            { "Thermometer2", "\uf2c9" },
            { "Thermometer3", "\uf2c8" },
            { "Thermometer4", "\uf2c7" },
            { "ThermometerEmpty", "\uf2cb" },
            { "ThermometerFull", "\uf2c7" },
            { "ThermometerHalf", "\uf2c9" },
            { "ThermometerQuarter", "\uf2ca" },
            { "ThermometerThreeQuarters", "\uf2c8" },
            { "ThLarge", "\uf009" },
            { "ThList", "\uf00b" },
            { "ThumbsDown", "\uf165" },
            { "ThumbsOutlineDown", "\uf088" },
            { "ThumbsOutlineUp", "\uf087" },
            { "ThumbsUp", "\uf164" },
            { "ThumbTack", "\uf08d" },
            { "Ticket", "\uf145" },
            { "Times", "\uf00d" },
            { "TimesCircle", "\uf057" },
            { "TimesCircleOutline", "\uf05c" },
            { "TimesRectangle", "\uf2d3" },
            { "TimesRectangleOutline", "\uf2d4" },
            { "Tint", "\uf043" },
            { "ToggleDown", "\uf150" },
            { "ToggleLeft", "\uf191" },
            { "ToggleOff", "\uf204" },
            { "ToggleOn", "\uf205" },
            { "ToggleRight", "\uf152" },
            { "ToggleUp", "\uf151" },
            { "Trademark", "\uf25c" },
            { "Train", "\uf238" },
            { "Transgender", "\uf224" },
            { "TransgenderAlt", "\uf225" },
            { "Trash", "\uf1f8" },
            { "TrashOutline", "\uf014" },
            { "Tree", "\uf1bb" },
            { "Trello", "\uf181" },
            { "Tripadvisor", "\uf262" },
            { "Trophy", "\uf091" },
            { "Truck", "\uf0d1" },
            { "Try", "\uf195" },
            { "Tty", "\uf1e4" },
            { "Tumblr", "\uf173" },
            { "TumblrSquare", "\uf174" },
            { "TurkishLira", "\uf195" },
            { "Tv", "\uf26c" },
            { "Twitch", "\uf1e8" },
            { "Twitter", "\uf099" },
            { "TwitterSquare", "\uf081" },
            { "Umbrella", "\uf0e9" },
            { "Underline", "\uf0cd" },
            { "Undo", "\uf0e2" },
            { "UniversalAccess", "\uf29a" },
            { "University", "\uf19c" },
            { "Unlink", "\uf127" },
            { "Unlock", "\uf09c" },
            { "UnlockAlt", "\uf13e" },
            { "Unsorted", "\uf0dc" },
            { "Upload", "\uf093" },
            { "Usb", "\uf287" },
            { "Usd", "\uf155" },
            { "User", "\uf007" },
            { "UserCircle", "\uf2bd" },
            { "UserCircleOutline", "\uf2be" },
            { "UserMd", "\uf0f0" },
            { "UserOutline", "\uf2c0" },
            { "UserPlus", "\uf234" },
            { "Users", "\uf0c0" },
            { "UserSecret", "\uf21b" },
            { "UserTimes", "\uf235" },
            { "Vcard", "\uf2bb" },
            { "VcardOutline", "\uf2bc" },
            { "Venus", "\uf221" },
            { "VenusDouble", "\uf226" },
            { "VenusMars", "\uf228" },
            { "Viacoin", "\uf237" },
            { "Viadeo", "\uf2a9" },
            { "ViadeoSquare", "\uf2aa" },
            { "VideoCamera", "\uf03d" },
            { "Vimeo", "\uf27d" },
            { "VimeoSquare", "\uf194" },
            { "Vine", "\uf1ca" },
            { "Vk", "\uf189" },
            { "VolumeControlPhone", "\uf2a0" },
            { "VolumeDown", "\uf027" },
            { "VolumeOff", "\uf026" },
            { "VolumeUp", "\uf028" },
            { "Warning", "\uf071" },
            { "Wechat", "\uf1d7" },
            { "Weibo", "\uf18a" },
            { "Weixin", "\uf1d7" },
            { "Whatsapp", "\uf232" },
            { "Wheelchair", "\uf193" },
            { "WheelchairAlt", "\uf29b" },
            { "Wifi", "\uf1eb" },
            { "WikipediaW", "\uf266" },
            { "WindowClose", "\uf2d3" },
            { "WindowCloseOutline", "\uf2d4" },
            { "WindowMaximize", "\uf2d0" },
            { "WindowMinimize", "\uf2d1" },
            { "WindowRestore", "\uf2d2" },
            { "Windows", "\uf17a" },
            { "Won", "\uf159" },
            { "Wordpress", "\uf19a" },
            { "Wpbeginner", "\uf297" },
            { "Wpexplorer", "\uf2de" },
            { "Wpforms", "\uf298" },
            { "Wrench", "\uf0ad" },
            { "Xing", "\uf168" },
            { "XingSquare", "\uf169" },
            { "Yahoo", "\uf19e" },
            { "Yc", "\uf23b" },
            { "YCombinator", "\uf23b" },
            { "YCombinatorSquare", "\uf1d4" },
            { "YcSquare", "\uf1d4" },
            { "Yelp", "\uf1e9" },
            { "Yen", "\uf157" },
            { "Yoast", "\uf2b1" },
            { "Youtube", "\uf167" },
            { "YoutubePlay", "\uf16a" },
            { "YoutubeSquare", "\uf166" },
        };

        public SymbolIconTag SymbolTag { get; private set; }

        internal void Update(SymbolIconTag dataTag)
        {
            this.SymbolTag = dataTag;
            this.SetTextAndFontFamily(dataTag);
            this.SetFontSize();
        }

        private void SetTextAndFontFamily(SymbolIconTag tag)
        {
            switch (tag.SymbolType)
            {
                case SymbolType.Glyph:
                    if (!string.IsNullOrWhiteSpace(tag.FontFamily))
                    {
                        this.FontFamily = new System.Windows.Media.FontFamily(tag.FontFamily);
                    }
                    else
                    {
                        this.FontFamily = new System.Windows.Media.FontFamily("Segoe MDL2 Assets");
                    }

                    this.Text = this.GetUnicode(tag.SymbolName) ?? string.Empty;

                    break;

                case SymbolType.Symbol:
                    this.FontFamily = new System.Windows.Media.FontFamily("Segoe MDL2 Assets");
                    this.Text = KnownSymbols.ContainsKey(tag.SymbolName) ? KnownSymbols[tag.SymbolName] : string.Empty;
                    break;

                case SymbolType.FontAwesome:
                    this.FontFamily = new System.Windows.Media.FontFamily($"file:///{System.IO.Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)}/SymbolVisualizer/FontAwesome.otf#FontAwesome");

                    this.Text = KnownFontAwesomeIcons.ContainsKey(tag.SymbolName) ? KnownFontAwesomeIcons[tag.SymbolName] : string.Empty;
                    break;

                default:
                    System.Diagnostics.Debugger.Break();
                    break;
            }
        }

        private string GetUnicode(string symbolName)
        {
            var regex = new Regex(@"[a-f1-9]{2,4}", RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.IgnoreCase);
            if (regex.IsMatch(symbolName))
            {
                return ((char)Convert.ToInt32($"0x{symbolName.ToLowerInvariant()}", fromBase: 16)).ToString();
            }

            return null;
        }

        private void SetFontSize()
        {
            if (this.vsFontSize is null)
            {
                DTE vsEnvironment = (DTE)ServiceProvider.GlobalProvider.GetService(typeof(SDTE));

                if (vsEnvironment != null)
                {
                    Properties propertiesList = vsEnvironment.get_Properties("FontsAndColors", "TextEditor");
                    Property pFontSize = null;
                    ColorableItems pPlainText = null;

                    if (propertiesList != null)
                    {
                        pFontSize = propertiesList.Item("FontSize");

                        var fandcItems = propertiesList.Item("FontsAndColorsItems") as EnvDTE.Property;
                        var fcList = fandcItems.Object as EnvDTE.FontsAndColorsItems;

                        pPlainText = fcList.Item("Plain Text");
                    }

                    if (pFontSize != null)
                    {
                        this.vsFontSize = Convert.ToDouble(pFontSize.Value.ToString());
                    }

                    if (pPlainText != null)
                    {
                        this.vsPlainTextForeground = pPlainText.Foreground;
                    }
                }
            }

            if (this.vsFontSize.HasValue)
            {
                this.FontSize = this.vsFontSize.Value;
            }

            if (this.vsPlainTextForeground.HasValue)
            {
                Color UIntToColor(uint color)
                {
                    ////var a = (byte)(color >> 24);
                    var r = (byte)(color >> 16);
                    var g = (byte)(color >> 8);
                    var b = (byte)(color >> 0);
                    return Color.FromArgb(255, r, g, b);
                }

                this.Foreground = new SolidColorBrush(UIntToColor(this.vsPlainTextForeground.Value));
            }
        }
    }
}
